### ISSUE TITLE
Not compressing as well as Photoshop

### ISSUE THREAD

**Issue by Barn2** [Gifox/Tracker#105]
I created a gif in Gifox and when I open and re-save it in Photoshop, the file size reduces from 607KB to 568KB without needing to change any settings. 

In addition, Photoshop allows me to experiment with different options and tells me how this will affect the file size, so I can experiment with each individual gif and use the preview window to find the right balance of quality vs. file size. 

GIFOX SETTINGS
Record fp2 12.5
Downscale 0.50
Playback fps 17.5
Max colours: 64
Palette: All frames
Dither: None

PHOTOSHOP SETTINGS
Selective
No Dither
Transparency enabled
Interlaced disabled
Colors: 64
Web Snap: 0%
Lossy: Disabled
Image size: (no change)
Quality: Bicubic

![gifox](https://user-images.githubusercontent.com/45937378/53252812-afed7280-36b7-11e9-8547-5c3dbe4e97e5.gif)
![photoshop](https://user-images.githubusercontent.com/45937378/53252819-b24fcc80-36b7-11e9-96dd-a23150537a58.gif)

**Comment by iby** [comment]
I'm going to close this down. In case this helps anyone, we discussed this with Katie over the email and my general response was:

> If you feel you went all out with finding the optimal file size vs quality settings and saying that the Photoshop beats the crap out of Gifox… then I don't have reasons not to believe you. Gifox uses open source FFmpeg framework for compression, which does an amazing job by the way. Folks at Photoshop might have developed their own proprietary algorithm that performs way better, after all they do have the resources. But again, there are several factors involved where the actual compression algorithm might not play the biggest role.

I checked both GIFs, both look very similar and size difference is pretty negligible. If this is critical, I can suggest using [ImageOptim](https://imageoptim.com/mac) to bulk-process your recordings. Please note, that it might impact the image quality, but this is a great option with quite a few settings to play with.
