### ISSUE TITLE
10 second limitation in free version

### ISSUE THREAD

**Issue by cdschwartz** [Gifox/Tracker#106]
Please notify users about the free version having a 10 second limitation on the length of gifs.

I have no issue with the limitation, but I almost went to a competing product because I did now know about the limitation. I assumed that the application crashed or it were a general  limitation.

**Comment by ianbytchek** [comment]
@cdschwartz Thanks for reporting this! Yes, it is an ongoing problem, apologies… 😔 One thing we didn't want doing is slamming our users in the face with "free version, purchase a pro" pop ups and the bright orange "Unlock Full Version" button seemed like a good way out of this. Obviously not, given the amount of recent feedback.

We're finishing the Gifox 2 release and here's what will probably do:
- Let users know as part of the welcome screen that there's a Pro version with benefits.
- Inside the selection UI (either during pre-selection or within selection toolset) indicate that recording is limited and watermark is forced.
- Probably move licensing into preferences.

Ideas and suggestions are welcome! ✌️

**Comment by ianbytchek** [comment]
Since v2.0.0 release we show detailed information about the benefits of Gifox Pro in welcome and licensing dialogs. I feel this is no longer an issue. If you think otherwise please feel free to reopen the issue! ✌️
