### ISSUE TITLE
Default keyboard shortcut (CMD-Shift-5) used by Mojave utility

### ISSUE THREAD

**Issue by drawcard** [gifox/tracker#107]
MacOS Mojave's built in screenshot utility uses Cmd-Shift-5 to provide a richer UI for taking screenshots: http://www.loopinsight.com/2018/06/28/mojave-and-shift-command-5/ 

Unfortunately Gifox claims this shortcut by default and it overrides Mojave's settings.

I'm aware you can change this to something else in Gifox but it would be nice to not have to manually configure this per installation. Could I please suggest Gifox uses other default shortcuts eg Cmd-Shift-6 / Cmd-Shift-7?

**Comment by ianbytchek** [comment]
I can only keep quietly drowning in shame with macOS Catalina already on the horizon and Gifox  Mojave support is still only in Beta… It's available [here](https://gifox.io/prerelease) and packed with lots of improvements and new features. The new Beta build is coming up in a couple of days. So gonna close this ticket down.
