### ISSUE TITLE
Save as mp4 (sorry)

### ISSUE THREAD

**Issue by aaronpeterson** [Gifox/Tracker#109]
Would it be possible for your to allow us to save the captured video as an h264 video file?  I know it's outside the scope of this software but you have to realize there isn't anything on the market as elegant in terms of capture flow (that I've found).

Yeah.  I had to come back and edit this.  I just looked at "SnagIt" again and I can't.  Snag-it is $50.  It is hideous.  I just want you to stop your processor before the convert to gif part.  I will pay $50 for this feature. 

Also I still need the downscaling feature.  Throw in a "mp4 quality" slider thing and I will pay $150.  I know I'm not the only one.

**Comment by jiaweihli** [comment]
Yes please on mp4 support.  My workflow at the moment is running `ffmpeg` to convert the GIF back into a video :|

**Comment by ianbytchek** [comment]
Okay, we finally have a solution for this without bloating the app. This is tracked in #130.
