### ISSUE TITLE
Click animations not place in the right location

### ISSUE THREAD

**Issue by carlosperate** [Gifox/Tracker#111]
In beta.3:

![2019-09-05 14 46 52](https://user-images.githubusercontent.com/4189262/64347632-261a4c80-cfec-11e9-8d8a-1292a26e8ad1.gif)

Maybe due to the window shadow?

**Comment by carlosperate** [comment]
Also it can be seen in that gif that issue https://github.com/Gifox/Tracker/issues/97 is still present.

**Comment by ianbytchek** [comment]
Thanks for reporting this! I believe this is fixed in the upcoming build, but let's keep this open just in case. This should behave as expected with free-area selection mode.

**Comment by ianbytchek** [comment]
Must be fixed in the latest beta build (04).

**Comment by carlosperate** [comment]
Awesome, thanks for all the great work!
