### ISSUE TITLE
Only records background after upgrade to OSX Catalina

### ISSUE THREAD

**Issue by jdaily** [Gifox/Tracker#114]
When selecting a sub-section of the screen to record, only the desktop background gets saved. When recording the entire screen gifox crashes.

**Comment by ianbytchek** [comment]
Catalina brought strengthened security and privacy protection to prevent apps without explicit access to record your screen. Please go to System Preferences > System Preferences > Security & Privacy > Privacy > Screen Recording and grant Gifox the access, that should do it.

**Comment by sfentress** [comment]
How can I get Gifox to re-request the permissions? After the upgrade (macOS 10.15.2) I don't see Gifox in the Privacy > Screen Recording window.

<img width="1153" alt="Screen Shot 2020-02-26 at 12 10 44 PM" src="https://user-images.githubusercontent.com/35721/75369352-4a672f80-5891-11ea-80e5-09561d8fde1f.png">

**Comment by sfentress** [comment]
On a possibly-related note, every time I select the "Select window for recording" button, and then mouse over a window, the app crashes. I assume this somehow relates to the app not having permissions.

**Comment by ianbytchek** [comment]
Apologies, the main issue for some reason didn't get linked here. Yes, the crash is caused by the lack of permissions, please see #115 for further details. Let know if something doesn't work out?
