### ISSUE TITLE
Feature request: Capture the pop up with window selection

### ISSUE THREAD

**Issue by Tungtono** [Gifox/Tracker#118]
I haven't seen it requested here and I don't know if it's possible, but can you somehow capture the popup from the current window.

How I expect it?

1. Start a screen record with Window selection (it's very nice btw).
2. Have some actions on the window that trigger the pop up, such as a right click.
3. Gifox can include that right click menu in the record. I hate when I recorded a really nice window but then found out that the popup wasn't included, then I had to switch to area selection and record again. And the area selection is not as nice.

Thanks!

**Comment by ianbytchek** [comment]
This is a real bummer, sorry. Unfortunately there's not much we can do about it, see the related https://github.com/Gifox/Tracker/issues/55#issuecomment-354533842 for details & workaround. There's a private API for that somewhere, but we couldn't figure it out the last time when looked into it. If you happen to know any apps that can do that (apart from the standard macOS screen capture) or someone else who might know a workaround, I'd really appreciate any tips!
