### ISSUE TITLE
Gifox doesn't show up in screen recording privacy settings on macOS Catalina

### ISSUE THREAD

**Issue by ianbytchek** [Gifox/Tracker#121]
**Update:** This should be fixed in 2.0.2, please let us know if the issue remains?

In some instances Gifox wouldn't appear in system screen recording privacy settings, pressing the "Authorize Gifox" button in the authorization request dialogue wouldn't do anything. This is related, but not the same as issue #116. The below illustrates what should happen.

![gifox-github-121](https://user-images.githubusercontent.com/1086845/69862679-e71a3100-1292-11ea-9be3-fc5fc664a3f0.png)

Here are the things you can try for sorting this out. Before you do, if you fix it using the below steps or find another solution, please leave a comment with what worked and what app distribution you're using ([direct](https://gifox.io), [Mac App Store](https://apps.apple.com/app/gifox-2/id1461845568?ls=1&mt=12) or [Setapp](https://go.setapp.com/stp122?refAppID=197)), it would greatly help us with putting better instructions. This is an awkwardly weird issue that we literally have no control over but it's on us to make sure that it works… 🤷

1. In 9 out of 10 cases the smaller `Screen Recording` dialogue with `Open System Preferences` button would appear behind other windows. Use mission control to find it or hide other windows and see if it's hidden behind them.
    - The system prevents the dialogue from appearing twice if you closed it before. You'd need to restart the app and try again.
    - Unless you press `Open System Preferences` or `Deny` the app won't appear in the recording privacy settings list and you won't be able to authorize it. So, **this part is crucial**!
    - If you're not launching the app directly then it's the parent app that would need authorizing in system preferences.
    - If the system preferences got open but you can't see Gifox in the list try scrolling up and down – it's a weirdly small box and might appear unscrollable.

2. In 1 out of 10 cases this might be a system glitch. Typically restarting helps to get things back to normal. If not, you can try resetting the privacy settings, but make sure you restart first. There's a one known case where this might cause the system being completely stuck after full privacy reset, so do this at your own risk and save any work first.
    - First, quit Gifox and try one of the following commands in Terminal: 
    `tccutil reset All com.gifox.gifox2` for direct-download v2 version; 
    `tccutil reset All com.gifox.gifox2-appstore` for Mac App Store v2 version.
    `tccutil reset All com.gifox.gifox-setapp` for all Setapp versions. 
    `tccutil reset All com.gifox.gifox` for all other v1 versions. 
    - If that doesn't help and you decide to go with the full privacy settings reset keep in mind that you will need to re-authorize other apps too. If there's a problem with macOS system you may get the same issue with other apps that were previously authorized. Now that you've been warned run `tccutil reset All` command in Terminal.

If you're still having the problem then the issue is most likely system-related. This is pretty much impossible to get wrong from the app side of things and the authorization approach is one and the same for every other app – simply ask the system to capture the screen and it asks the user to authorize. 

You can also try downloading a different distribution of the app, e.g., from [Mac App Store](https://apps.apple.com/app/gifox-2/id1461845568?ls=1&mt=12), [directly](https://gifox.io), or via [Setapp](https://go.setapp.com/stp122?refAppID=197), and if other apps are handling the privacy settings as expected then a different distribution is likely to work too – it would have a different bundle ID and would appear as a different and unrelated app to the system. In this case full system privacy reset should definitely do the trick, but if not, the other best option is to [contact Apple](https://support.apple.com/en-gb/contact).

**Comment by joopvos** [comment]
I bought v2 two days ago and couldn't activate Gifox in sytem prefs (screensharing). I just deleted every file (AppCleaner) and did a new download from the website. I got the free trial and could now activate Gifox screensharing in system prefs ... :) ... but couldn't activate licensing ... :( 

I again deleted every file and did a download from the purchase email. And happily there was the activation window and button for my license number ... :)

Everything is working fine!

**Comment by ianbytchek** [comment]
We didn't see any reports lately, so looks like this was fixed. Please let us know if we need to reopen this?

**Comment by peppy** [comment]
As a heads up, I reproduced this by:

- Downloading version from website, authorising successfully.
- Deciding to purchase pro, but via app store
- Deleting downloaded copy and downloading via app store
- Attempting to authorise using app store version
- Gifox doesn't show up in list

Going back to stand-alone install makes it appear and work as expected, so I'll stick with that for now.

**Comment by ianbytchek** [comment]
All distributions (direct-download, Mac App Store and Setapp) use their own bundle identifiers, so they all behave like different apps essentially. If you authorized the direct-download version, the system will see the Mac App Store version like a completely different app. So far we've seen a lot of cases where it goes wrong, most documented in this and related issues, however, resetting the system permissions and restarting worked so far every single time. I'd also recommend sticking with the direct-download version as it receivers updates much faster than other distributions and doesn't rely on external review (Apple / Setapp) – apart from this, all builds are exactly the same.

**Comment by peppy** [comment]
No worries, just provided my reproduction in case it was useful in tracking things down.

Really enjoying the app, by the way. I think I've finally found a gif recorder I can actually use (automatic copy to clipboard would be nice though – have to use a folder action for that for the time being).

**Comment by DiegoMagdaleno** [comment]
Hello, as a developer, I would like to contribute one more research point if none of this things work for you:

- Reenable system integrity protection

I was having this issue and none of this seem to help, so I went into recovery (cmd + R when booting your Mac) and reenabled SIP. Everything worked after!.

Hope this helps!.

**Comment by ianbytchek** [comment]
@DiegoMagdaleno Wow, thanks for the input, will add this into the main list. This is definitely a new piece of info. Do you know if there are any other apps that suffer from this? I'm a little surprised this is the first time I hear about this, not that I intentionally looked around, but pretty sure wouldn't miss this point! Just wonder if there are any other way around this… 🤔

**Comment by DiegoMagdaleno** [comment]
Hi, yeah other apps that suffer from this are Bartender for example, [reference](https://www.macbartender.com/b3_knowledge/bartender-not-in-screen-recording-preferences/). And no, sadly I didn’t find any workaround but going into recovery and enabling system integrity protection.

**Comment by peppy** [comment]
For what it's worth, I require SIP to be disabled for my development environment, and had it disabled throughout my testing above. Using the non-appstore version seems to function correctly with it still disabled.

**Comment by DiegoMagdaleno** [comment]
Interesting, I also need SIP disabled cuz I normally need full access to / :/

**Comment by ianbytchek** [comment]
Yes, this might be the case. App Store version is sandboxed and comes with extra system security, which probably relies a lot on SIP.

**Comment by DanielPower** [comment]
Had Gifox 1.x pro, was working fine.
Purchased and downloaded Gifox 2.2.0 from your website.
Gifox asked me to give it screen recording permission when I first tried to create a recording. So I did. Then I quit Gifox and re-launched it.

Gifox is still asking for recording permission every time, even though I've given it that permission. Making the app completely unusable.

OSX Catalina 10.15.4

**Comment by ianbytchek** [comment]
Hey Daniel, please make sure this is the screen recording permission request, not [accessibility control](https://github.com/Gifox/Tracker/issues/131) – two are easy to confuse. Please follow all suggestions at the top, especially restarting the Mac. When macOS experiences a glitch at this level, relaunching the app won't help, but restarting the system helps in absolute majority cases. System Integrity Protection must be enabled for system privacy permissions to work properly, so, check that it's enabled.

Again, there's nothing we'd like more than this working smoothly, but this is one of those issues that is completely outside out control. All an app can do is invoke a system function that triggers a screen capture – after that everything else is controlled by Apple to keep apps from messing with your security configuration. In rare cases this mechanism gets messed up and the above workarounds usually solve the problem. Hope this helps?

**Comment by DanielPower** [comment]
The permission I gave it was indeed the "Screen Recording" permission. Even after a reboot, it did not work, and gave me the same error every time I would try to take a recording.

Giving Gifox the Accessibility permission solved the problem though. So perhaps the permission handling is incorrect, or the error message should be updated to ask for both Screen Recording and Accessibility permissions. I can reproduce perfectly, I get the error message consistently if I uncheck Gifox under Accessibility, and no error message if I check Gifox under Accessibility.

Seems that I need to have both permissions enabled for it to work.

**Comment by ZuBB** [comment]
@DanielPower is right. 2 perm need to be issued. hope authors will be able to get better UX for that

**Comment by ianbytchek** [comment]
Thanks everyone for all of your input here. I might be missing a something, but yes, Gifox needs two different permissions, one for screen recording and one for accessibility control:

![](https://user-images.githubusercontent.com/1086845/92615333-e815cf80-f2b4-11ea-803b-35c7eec5cbfc.png)

It shows two very similar dialogs when either of them is disabled, both say a slightly different thing and take you to a different system preferences pane:

![](https://user-images.githubusercontent.com/1086845/92615890-8144e600-f2b5-11ea-9fcd-35e344ee7cac.png)

Please let me know if that's not what happening? On our side, we are planning to make things a little more distinct in upcoming releases to eliminate the confusion – I'm hoping this is the only issue?

**Comment by raulriera** [comment]
I can confirm this issue is happening now in Big Sur with MacBook Air M1

| Error  | Settings | System |
| ------------- | ------------- |  ------------- |
| <img width="612" alt="Screen Shot 2021-05-24 at 12 36 15 PM" src="https://user-images.githubusercontent.com/24159/119378772-a2efcd00-bc8c-11eb-8598-8188e4ac26c9.png"> | <img width="692" alt="Screen Shot 2021-05-24 at 12 36 50 PM" src="https://user-images.githubusercontent.com/24159/119378852-b733ca00-bc8c-11eb-92c5-443803456d7c.png"> | <img width="780" alt="Screen Shot 2021-05-24 at 12 37 35 PM" src="https://user-images.githubusercontent.com/24159/119378939-d3376b80-bc8c-11eb-8b9f-3446d97ab832.png">
 |
