### ISSUE TITLE
Gifox is crashing immediately after starting the recording 💥

### ISSUE THREAD

**Issue by ianbytchek** [Gifox/Tracker#122]
**Update:** This should be fixed for most cases in version 2.0.2. Let us know if you're still seeing the problem?

This is an isolated Gifox 2 issue and apparently is a complete show stopper for those who's getting it. We currently are not able to reproduce it and if you can send in-app feedback with logs and preferences attached it would help a lot. If you notice something what triggers this please let us know – this would be the most important piece of information for solving it.

If you're affected by this, please let us know:
1. Try disabling mouse and keyboard interaction capture in capture tab in preferences. If this helps, please isolate which options are responsible for the crash and let us know?
2. Does it happen all the time or the app was working before and could make recordings?
3. Does it go away if the record and playback frame rate are set to `1` in preferences and the recording is kept very short, literally with one or two frames in it?
4. Does restarting the Mac help at all?

We'll be trying some workaround in the upcoming update, but any input and details would be of great value! Bear with us!

**Comment by Eingang** [comment]
**Environment:** Mac OS X 10.13.6 (High Sierra). 27" iMac (late 2012).

1.  Disabling things: ✅ = enabled; ❌ = disabled.

	| Desc. | Cursor | Mouse Inter. | Keyboard Inter. | Result |
	| :--- | :---: | :---: | :---: | :---: |
	| All 3 enabled | ✅ |  ✅ | ✅ | 💥Crash |
	| All 3 disabled | ❌ | ❌ | ❌ | 🆗OK |
	| Just cursor | ✅ | ❌ | ❌ | 🆗OK |
	| Just mouse | ❌ | ✅ |  ❌ | 💥Crash |
	| Just keyboard | ❌ | ❌ | ✅ | 💥Crash |
	| Mouse + keyboard | ❌ | ✅ | ✅ | 💥Crash |

1. > Does it happen all the time or the app was working before and could make recordings?

    I'm a new user, so I can't say whether this ever worked previously. I can consistently make it happen or not by playing with the capture settings as detailed above.
 
 1. > Does it go away if the record and playback frame rate are set to 1 in preferences and the recording is kept very short, literally with one or two frames in it?

    * With 1 fps, there was a delay before the application crashed when the recording started. I might not have been fast enough to stop it. I can't set keyboard shortcuts (the tab is missing in preferences and "Sharing" is cut-off so it only shows "Sh").
    * Short recording: All my above experiments were literally starting the recording and it would crash. Where it succeeded, it seemed to have no problems with saving, even with more than a few frames.
        
1. > Does restarting the Mac help at all?
   
    I'm dubious it would and I had too much stuff I was in the middle of to want to do a restart.

**Comment by ianbytchek** [comment]
Could you give it another go with the latest 2.0.1 release (Mac App Store and Setapp versions are coming shortly). We partially narrowed down the issue to captured interaction rendering using hardware acceleration. In this release we reverted the api to older OpenGL in favour of Metal, so if this works we'll know better where to look.🤞

**Comment by elanals** [comment]
For me it's the exact same behaviour as before unfortunately :(

**Comment by elanals** [comment]
Seems like the workaround in the 2.02-beta works! :)

**Comment by elanals** [comment]
![gifox](https://user-images.githubusercontent.com/19191012/70341105-7a82d180-1852-11ea-9bee-b11a8a6b1af8.gif)

**Comment by ianbytchek** [comment]
This should be fixed as of 2.0.2 in 9 out of 10 cases. If you're still seeing this, please let know.

**Comment by ianbytchek** [comment]
Okay, version 2.1.0 addresses probably 99 out of 100 cases! 😅 Please give it a go and post back if we need to reopen the issue!

**Comment by tkrugg** [comment]
Unfortunately it doesn't. I'm using 2.3.0 and it consistency crashes after a few minutes of recording

**Comment by iby** [comment]
@tkrugg Do you mean as it crashes after making a few-minute-long recording or after making a short recording but a few minutes after that?

**Comment by tkrugg** [comment]
Hi @iby it crashes after making a few-seconds-long recording, 3 to 4 seconds.
