### ISSUE TITLE
Export resizing doesn't always work as expected

### ISSUE THREAD

**Issue by ianbytchek** [Gifox/Tracker#123]
Gifox 2 comes with the new export resizing controls… and they don't always work! 🤦 

Resizing can be controlled globally via export tab in preferences or individually per recording in editor export configuration. Sometimes when editing individual export configuration it also updates global settings, which might affect other individual configurations during export. So, if you notice your exported GIFs are wrong in size just double check the export configuration and try exporting once more. The fix is underway.

![gifox-github-123](https://user-images.githubusercontent.com/1086845/70123275-38973700-166a-11ea-9db2-91c8a74b6159.png)

**Comment by ianbytchek** [comment]
This must be fixed in 2.0.1. Please reopen if something is out of order.

**Comment by flaviolira123** [comment]
Hi Ian, I purchased it via the App store, is there a way to update it via the website and retain the App store license or should I wait for it to be pushed via App store? Thanks!

**Comment by ianbytchek** [comment]
The app was released yesterday in the App Store shortly after your comment. Another one with more improvements is coming in a day or two!

**Comment by flaviolira123** [comment]
Thanks! Mine has been uploaded to 2.0.1, but when I capture a gif, it still comes with super hi-res from the 5k display. 

On export, I have my resize settings to fit to 720w. Shouldn't the gifs already come with this resolution, or going through the edit window is needed at this point?

![image](https://user-images.githubusercontent.com/53919140/70396331-f2c5d000-19d5-11ea-826d-05ab625ee378.png)

**Comment by ianbytchek** [comment]
This will be fixed in 2.0.2. I only yesterday realized what the actual cause of the issue is – the global export configuration isn't applied to the initial recording export. For the time being, to ensure the configuration is correctly applied just open the editor and press `Done` to export it once more. The next update is expected in a day or two.
