### ISSUE TITLE
UI bug in settings navigation?

### ISSUE THREAD

**Issue by elanals** [Gifox/Tracker#124]
It's a bit difficult to navigate the settings due to the word truncation and the fact the last tab is essentially out of view. Seems like there may be a mistake here.

![Settings-UI](https://user-images.githubusercontent.com/19191012/70259232-0bdc4000-178e-11ea-90f6-2e99b1df7a6e.gif)

**Comment by ianbytchek** [comment]
We made adjustment for the upcoming release, but your's is worse that what we got reported so far. Is this happening on the older macOS, like 10.12 or 10.13?

**Comment by elanals** [comment]
Yeah, no Catalina yet, it's 10.13.6

**Comment by ianbytchek** [comment]
😯 Wow, okay… We're planning on publishing an update later on tonight. Please check then, hopefully it will be sorted, but I'm getting a feeling there might be a catch. By the way, are you using the direct download version?

**Comment by elanals** [comment]
App downloaded from https://gifox.io/ if that answers the question?

**Comment by ianbytchek** [comment]
Yes. Thanks!

**Comment by ianbytchek** [comment]
@elanals Could you check if this got better in the 2.0.1 release?

**Comment by elanals** [comment]
Getting there :D

![image](https://user-images.githubusercontent.com/19191012/70325774-11d82c80-1833-11ea-8bb9-9da030cb0c29.png)

**Comment by ianbytchek** [comment]
🤦 Alright. I'm gonna start a new beta and will try other things. Just curious, what's that window with the app details? It's not ours is it?

**Comment by elanals** [comment]
Yes that's yours, I included opened it and included it in the screenshot just to make sure everyone's on the same page about which version, is being used here

**Comment by ianbytchek** [comment]
Just published 2.0.2 Beta, this seems to be fixed. Could you give it another go and confirm? Also, there's a new workaround for the crashing issue, if you could check that too, would be fantastic. P.S. I double checked everything and can't locate that info window anywhere in sources. Could you let me know how you brought it up?

**Comment by elanals** [comment]
👍

![image](https://user-images.githubusercontent.com/19191012/70340567-49ee6800-1851-11ea-86fe-b4e45c9ec440.png)

As for mystery info window, maybe apple does this automatically? 
In the Menu Bar **Gifox** > **About Gifox**
![image](https://user-images.githubusercontent.com/19191012/70340682-8a4de600-1851-11ea-876d-c6c26e503218.png)

**Comment by ianbytchek** [comment]
Ha, yes, that must be a generic thing. Got curious because it supposed to look like below. One issue out, one issue in.

![image](https://user-images.githubusercontent.com/1086845/70351226-6219b380-1860-11ea-93b5-66cb28cea650.png)
