### ISSUE TITLE
Gifox is crashing when making or changing selection 💥

### ISSUE THREAD

**Issue by ianbytchek** [Gifox/Tracker#125]
Apparently, this happens during the actual selection, not when recording or exporting. This is thought to be related to #122 but not the same. The issue so far has been observed only on macOS Catalina and affects <1% of users. We weren't able to reproduce it and from what we know it doesn't happen all the time, so if you can provide any input it would be of massive help:

1. How often does it happen and are there any patters that could help reproducing this?
2. Is it more likely to happen on second / third selection or doesn't matter?
3. Is it more likely to happen during active export session?
4. Is it more likely to happen when CPU / GPU under a higher load?

**Comment by chadalen** [comment]
I have this problem but it only happens on my work's 2015 15" Macbook Pro. I think this might be related to the graphics card. On my 2019 15" Macbook Pro this doesn't happen.

1. I can replicate it 100% of the time. The pattern is it doesn't like making a large selections e.g almost taking up the entire window.
2. No happens every time.
3. No
4. No, happens with no other programs opened.

**Comment by ianbytchek** [comment]
Same as #139 – see it for further details.
