### ISSUE TITLE
Editor lacks a play/pause button

### ISSUE THREAD

**Issue by Nigelw** [Gifox/Tracker#126]
Sometimes I want to hit a play/pause button in the editor, and I get confused when I can't find one. Hitting spacebar is fine, but feels like an odd UI omission.

**Comment by ianbytchek** [comment]
Wow, thanks for pointing this out! At first I thought the assets might have gone missing in one of the recent cleanups, but it seems to be something else. Will make sure it's fixed in the upcoming update.

**Comment by ianbytchek** [comment]
Fixed in the upcoming release. 👍
