### ISSUE TITLE
Allow previewing of output framerate in editor

### ISSUE THREAD

**Issue by Nigelw** [Gifox/Tracker#127]
By default Gifox records at 15fps and outputs at a slightly sped up 17.5fps. It would be handy if the editor allowed you to playback captures at the output framerate so you can see what you'll be producing more accurately.

**Comment by ianbytchek** [comment]
This was implemented in latest 2.2.0 release. We reworked that part, now you can set the video frame rate in editor and use speed multiplier control to adjust the playback speed, so, two settings are now independent of each other and do exactly what they should! :)

**Comment by Nigelw** [comment]
The speed multiplier doesn't seem to affect the playback speed in the editor. (It does affect the output gif as expected.)

Still, 2.2.0 is an awesome release! 👏👏👏

**Comment by yabloki** [comment]
My biggest issue is with size of the gifs. Why the decrease of frames per second does not affect the speed of the resulted gif?
