### ISSUE TITLE
1x option for gifs recorded on retina screens

### ISSUE THREAD

**Issue by maxhoffmann** [gifox/tracker#13]
Hey there!

Would be great, if there was an option to save the gif with half the size (1x) when recording on a retina screen.

**Comment by ianbytchek** [comment]
Good idea. Backlogged.

**Comment by flukeout** [comment]
+1 to this - I've had trouble uploading / sharing my gifs via Twitter because they are massively wide.

**Comment by ianbytchek** [comment]
It is a pain in the ass, I know, especially because of #28. Aiming to deliver in 1.2.2-1.2.3 release. Stay tuned.

**Comment by dimitrieh** [comment]
yes it would be great to have this option, perhaps even along with a function for at start of recording

- 1/2 resolution
- 1/4 resolution


Perhaps when you click on this element before starting a recording:
![image](https://cloud.githubusercontent.com/assets/429659/19860238/4a783a0c-9f88-11e6-8745-289d6ba0de88.png)

it will change to:

- `1/2 * 98x82`
- `98x82 (1/2)`
- `48x41`
 
or even:

- `1/4 * 98x82`
- `98x82 (1/4)`
- `24x20`

**Comment by ianbytchek** [comment]
@dimitrieh wowow this is a really good idea! Will play with it! P.S. That's what coming later this week – absolutely loving it!

![image](https://cloud.githubusercontent.com/assets/1086845/19861049/8072eafa-9fa4-11e6-852a-34e9651ab137.png)

**Comment by ianbytchek** [comment]
Gifox 2 will be shipped with an editor. All content is now captured in real size and default export resizing can be configured through preferences.
