### ISSUE TITLE
Gifox keeps asking for accessibility permissions

### ISSUE THREAD

**Issue by ianbytchek** [Gifox/Tracker#131]
In recent Gifox 2.x versions the app will ask for accessibility control permission, in rare cases when you enable it Gifox won't recognize the access is granted and will continue asking again and again. This is identical to #116 issue, but with accessibility control instead of screen recording permissions.

Version 2.0.1 shipped with new accessibility control permission check, the app needs it to be able to track keyboard interactions when inactive in order to display them in your recordings. The issue is most likely to be caused by a system glitch as there are a few similar reports on the Internet without definitive solutions. It's pretty hard to get this wrong from the app perspective, it simply asks the system whether it has access or not and the dialogue is displayed based on that.

Try following suggestions and please leave/upvote a comment saying what worked to help us troubleshoot this better:

1. Remove the app from accessibility control pane and add it again manually.
2. Restart machine.
3. Try step 2 from #121.
4. Disable keyboard interaction capturing in app preferences.

**Comment by virth** [comment]
Just updated from free Gifox (version 1) to Gifox 2.1.0 Pro Version and had exactly this issue with macOS Mojave 10.14.5

Step 1 didn't help. Restarting the machine solved the problem.

**Comment by tbuckel** [comment]
What worked for me was manually adding Gifox:
![image](https://user-images.githubusercontent.com/1103738/74414398-53f99c00-4e7c-11ea-809f-1aacae1726ec.png)

**Comment by jdgarcia** [comment]
Manually adding Gifox did not work for me

**Comment by mani2care** [comment]
is there any command to add the any of app to the list in accessibility

**Comment by ianbytchek** [comment]
There's tccutil, can read about it [here](https://eclecticlight.co/2018/09/17/managing-mojaves-privacy-protection-privacy-controls). AFAIK, it only allows to reset the permissions. macOS is very protective of privacy settings, which is why the only adequate way to change them is manually though system preferences, otherwise other apps can mess with it behind your back.
