### ISSUE TITLE
Feature Request: Resize by percentage

### ISSUE THREAD

**Issue by hcsfred** [Gifox/Tracker#133]
I recently upgraded from Gifox 1 and it seems you can no longer resize by percentage. This is particularly useful for those with retina displays (to downsize by 50%).

**Comment by ianbytchek** [comment]
This and retina-only downscaling are coming back in the next release.

**Comment by ianbytchek** [comment]
This was implemented in 2.1.0. Apart from the Mac App Store, it's available for the download! ✌️
