### ISSUE TITLE
Gifox uses significant energy

### ISSUE THREAD

**Issue by ianbytchek** [Gifox/Tracker#135]
A few reports indicate that #79 might be back… Please help with the following info:

1. Open the Activity Monitor and see if the Gifox Media Service is running?
2. Create Gifox process sample and send it over. Please do the same for Gifox Media Service if it's running? See attached GIF for steps.
3. If Gifox Media Service is running, can you force-quit it and see in a few minutes if energy consumption goes back to normal?
4. If that doesn't help, can you try the same with the app itself? 
5. Relaunch it. Does it re-appear on the energy-offender list? If not, does it appear after making a recording?
5. What model of Mac are you using? Does it have two GPUs (discrete and integrated)?

![D9E73361698645B1BEE6F026113B5694](https://user-images.githubusercontent.com/1086845/74356120-bdfb3e00-4db5-11ea-96a1-164cf49238f6.gif)

**Comment by naoey** [comment]
Following up on my report on Twitter:

1. Gifox Media Service was initially not running, it ran for a bit and remained after the recording completed and then exited ~10 seconds later
2. Sample before and after recording respectively:
- [before.txt](https://github.com/Gifox/Tracker/files/4193685/Sample.of.Gifox.txt)
- [after.txt](https://github.com/Gifox/Tracker/files/4193705/Sample.of.Gifox.txt)
3. Gifox Media Service exited by itself, dGPU is still kept active by Gifox process
4. Quitting Gifox releases dGPU
5. Does not re-appear immediately, does re-appear after making a recording
6. MacBookPro16,1, (16" 2019)

**Comment by rogierslag** [comment]
> 1. Gifox Media Service was initially not running, it ran for a bit and remained after the recording completed and then exited ~10 seconds later

Same 

> 2. Sample before and after recording respectively:

I've added [a gist](https://gist.github.com/rogierslag/5cc6d75ab5497bc2ae3e0b4bc4b4834a) with 4 files

- Before
- Media services
- Gifox while media services ran
- Gifox after media services completed

> 1. Gifox Media Service exited by itself, dGPU is still kept active by Gifox process

Same

> 2. Quitting Gifox releases dGPU

Same

> 3. Does not re-appear immediately, does re-appear after making a recording

Same

> 4. MacBookPro16,1, (16" 2019)

<img width="317" alt="Screenshot 2020-03-20 at 14 36 54" src="https://user-images.githubusercontent.com/2778689/77168523-4311fb00-6ab8-11ea-9b54-a4f599d96f0c.png">

**Comment by ianbytchek** [comment]
Thanks for detailed reports guys, much appreciated. Will be honest, this not the best news – this issue is like a black box inside a black box. The only thing that comes to mind right now, is GPU acceleration we're using for interaction capturing. Can I ask to check if disabling interaction capturing has any effect on this after the Media Service terminates itself?

**Comment by naoey** [comment]
Oh hey that seems to be right on the money! It hadn't occurred to me and I just re-tested with 4 configurations in these options:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/3889501/77171520-94cf7b00-6ae2-11ea-83b1-89574f8a41c5.png">

The issue does not present itself with all of them off, with just cursor, and with cursor + background. It *did* occur again as soon as I enabled mouse interactions. I imagine it might be the same for keyboard as well although I didn't test it.

Interactions capture does seem to be the culprit!

**Comment by ianbytchek** [comment]
BINGO! Now we're talking! Yes, all interaction capturing share the common rendering mechanics, so the result should be the same. @rogierslag are you seeing the same results?

Next steps. We had a build before which was using the new Metal API on newer macOS versions for pixel crunching, but it would randomly crash from time to time, so we reverted everything back to OpenGL. I'll prepare the new build in a few days with Metal API instead of OpenGL to see if this is OpenGL related. From there on we can fix this ourselves or get help from Apple to see what's causing this. 

But this is a fantastic discovery! If we can get rid of the Media Service it can speed up GIF transcoding by >100%!!!

**Comment by rogierslag** [comment]
For now I've just tested single options. Seems to confirm the suspicion

- cursor selected: no problem
- mouse selected: problem
- keyboard selected: problem
- window selected: no problem
- background selected: no problem

**Comment by rogierslag** [comment]
Any updates by any chance?

**Comment by ianbytchek** [comment]
Yes, the upcoming release includes a tweak for better handling the automatic GPU switching, it will be available in a couple of days (definitely this week). Just running a little late with another tweak that turned out more time consuming than originally hoped, hence the delay.

**Comment by ianbytchek** [comment]
Hello friends, sorry for the delay, this release was a tough cookie. Just re-published 2.1.3, but looks like you'll need to get it manually from our website until we figure out issue 1572 with [auto-updates](https://github.com/sparkle-project/Sparkle/issues).

Please give it a go and let me know if it's any better? Like per @rogierslag [comment](https://github.com/Gifox/Tracker/issues/135#issuecomment-601734015), when using interaction capturing the GPU should now switch back to integrated shortly after finishing all recording and exporting. 🤞

**Comment by naoey** [comment]
I happen to be using the App Store version of Gifox. Is there a plan to push this update to that channel soon-ish?

**Comment by ianbytchek** [comment]
@naoey it's pending review, hoping to see it published today/tomorrow.

**Comment by ianbytchek** [comment]
Apple didn't like the screenshots that haven't changed in months – I feel we are being punished for others' sins! 😅 In any case, 2.1.3 is available through all channels. Very eager to hear if there are any changes?

**Comment by naoey** [comment]
Doesn't seem to be using the discrete GPU at all now, not sure if that was intended. But I can confirm that the problem initially being addressed here is now gone!

**Comment by rogierslag** [comment]
Same, no longer seems to occur!

**Comment by ianbytchek** [comment]
AWESOME!!! Super glad it did the trick, thanks for testing and feedback fellas, much appreciated!

> Doesn't seem to be using the discrete GPU at all now, not sure if that was intended.
That's okay. In that particular instance it only needs the GPU for a tiny render, which I'm sure can be easily handled by the integrated unit.

I mentioned that we solved this issue initially by moving the rendering from the main app into a service, which would get involved only during GIF export, which crippled the performance. So, with the real problem finally solved we'll revert this back and probably do beta testing first. Would appreciate if you can give it a go and let know if it's acting nicely.

**Comment by ianbytchek** [comment]
Friends, Gifox 2.2.0 Beta was just published and available for update, make sure to enable prerelease updates in general preferences. It takes further the progress made with this issue and I need your input to confirm there are no regressions. The next public release is going to be awesome! 👍
