### ISSUE TITLE
Playback speed on recording

### ISSUE THREAD

**Issue by mike182uk** [Gifox/Tracker#136]
Hey

I've noticed when I have recorded something, when i view the gif in the browser or some other gif previewer, its almost as if its playing back at 1.5x - 2x speed. If i go to edit the gif via the gifox editor, make no changes and press the `done` button, the GIF is updated and plays back at the expected speed.

Gifox `2.1.1`
macOS `10.15.2`

**Comment by ianbytchek** [comment]
Will look into this. Can you confirm the browser used for the previewing and the current recording and export playback frame rate? Can you also verify the export frame rate is the same in export configuration inside the editor?

**Comment by mike182uk** [comment]
Hey @ianbytchek

Im using the latest version of chrome, but even when previewing in finder the playback speed is quick.

Im using the app defaults for recording, and then the app defaults when editing. In both cases the frame rate is `17.5`.

Here is an example

**Original**:

![original](https://user-images.githubusercontent.com/991592/74587781-c9857980-4fee-11ea-94dd-277757fce702.gif)

**Edited** (but no settings changed):

![2020-02-15 12 24 41](https://user-images.githubusercontent.com/991592/74587788-d7d39580-4fee-11ea-8ddd-57da6f961b4f.gif)

And here are the settings:

**App Settings**:

<img width="587" alt="Screenshot 2020-02-15 at 12 32 00" src="https://user-images.githubusercontent.com/991592/74587841-7eb83180-4fef-11ea-845d-f90fe12b8a1e.png">

**Edit Settings**:

<img width="430" alt="Screenshot 2020-02-15 at 12 33 56" src="https://user-images.githubusercontent.com/991592/74587843-811a8b80-4fef-11ea-8d85-61130750337e.png">

Interesting note on that edit settings dialog: it says the source frame rate is 15.0 f/s. Shouldn't it be 17.5 f/s as per the settings?

**Comment by eerikson** [comment]
+1 on this, though I'm not sure if it's a UI change. I seem to be having lots of trouble lining up recording vs playback framerate, which I never had before. Cranking both to 50 gives a crazy-fast playback on Chrome, when all I want is a GIF captured and played at 50 fps.

**Comment by ianbytchek** [comment]
Thanks for detailed feedback. I'll look into this further this. 

In the meanwhile, below is a general note on capturing, playback and (cc @eerikson) on high fps. This is not why it's happening in @mike182uk case, but stands true for all GIFs in general.

GIF playback playback speed a tricky subject as it is implemented differently by different browsers and software in general, which often produces different results. For example, the same GIF opened in Chrome and Safari may play at different speed, with different end-pause, different looping behaviour, etc. Most engines would cap the playback fps, so it doesn't make sense to push fps above 30 especially for larger GIFs. Standard macOS apps like Preview and Safari don't handle it best, so I'd use Chrome as the control tool. That said, Gifox tries to make it as compatible as possible with all of the engines and the current compatibility proved to be fairly good. At the same time, GIF is simply not the best format for precision timing, though, you can always adjust the playback speed in the editor output configuration to get the desired result.

There's a bunch of things with capturing and conversion that make it challenging. For example, the screen is typically redrawn every 60 (or 30) frames with little deviations, depending or monitor, graphics card, system load, etc. At the same time there's no guaranteed way to make a capture at the given time – these time differences are, of course, very small and not visible to a naked eye, but when the system is under a high load, frames get skipped and we end up with less than expected number of frames, which quickly adds up. Capturing mode (window / area) may also affect the results. The number of factors is pretty ridiculous for what might seem a simple recording.

**Comment by ianbytchek** [comment]
This is fixed in the upcoming release in a few days. ✌️

**Comment by jiaweihli** [comment]
I only started seeing this bug a few days ago, on version 2.12 00
It's affecting all my GIFs, but the workaround seems to be working.

**Comment by jiaweihli** [comment]
It looks like this affects window selection mode, but not area selection mode.

**Comment by ianbytchek** [comment]
Hello friends. This must be fixed in 2.1.3. The App Store version is still pending review, but should be published soon. Let me know if we you feel we missed something?
