### ISSUE TITLE
[Feature Request] Allow trimming pixels of gif in the editor

### ISSUE THREAD

**Issue by sarfata** [Gifox/Tracker#140]
Would be very helpful if I could trim the gif (for example to remove the browser address bar) in the editor. I know I can use the area-selection mode but it's very painful to re-adjust the selection every time to what I want and selecting the window is much easier and reproducible.

Great product!

**Comment by ianbytchek** [comment]
Hey Thomas, thanks for the compliment! I believe you've got the latest version 2 and that's what you're using? We talked about editing and re-export in [release highlights](https://medium.com/gifox/gifox-2-is-here-release-highlights-bc93e670388d).

Open the recording, select the track and use handles on each end to trim it. There's also a blade tool in case you need to cut mid-parts out. P.S. Something is wrong with cursors when I'm trying to record Gifox using itself, will look into this! 🤷‍♂️

![2020-03-19 11 42 59](https://user-images.githubusercontent.com/1086845/77064358-42edfe80-69d7-11ea-9c29-9a128ee329f3.gif)

Feel free to reopen the issue if I missed something?

**Comment by sarfata** [comment]
Yes I found these features and loved them. Especially the cut tool. Very useful when you do a blooper in a demo ;)

What I am looking after is a way to trim in space and not in time. I want to remove the top 30 pixels in the video (for example because I recorded the whole browser window but I want to keep only the content). I think this would be useful for a lot of people to record a wide zone and then select just what they actually need to reduce the size of the file.

**Comment by ianbytchek** [comment]
Ah, yes. This is called cropping by the way! :) This is on the list. We're still sorting out some rare but rather critical post-release issues. Once they are off the list in a few weeks will start working on new features. Cropping is amongst top priorities.

**Comment by iby** [comment]
@sarfata I'm doing some housekeeping and cleaning up old issues. In case you missed the news, cropping support was released a few months ago, it's available in the editor:

![2023-03-02 19 25 34](https://user-images.githubusercontent.com/1086845/222531855-9f7681e5-ed3d-4265-89b2-a89de64d71c2.gif)

**Comment by sarfata** [comment]
WOOT WOOT!
