### ISSUE TITLE
[Minor] Updater UI bug in Dark Mode

### ISSUE THREAD

**Issue by dkarter** [Gifox/Tracker#144]
Users with Dark Mode enabled on their mac will see the changelog in the updater with a dark font on a dark background. See screenshot:

![CleanShot 2020-04-07 at 14 27 18@2x](https://user-images.githubusercontent.com/551858/78713068-42ae9800-78df-11ea-8c8b-6515997dd45d.png)

**Comment by ianbytchek** [comment]
Thanks for reporting and apologies for the lagged response. This should be fixed with the latest 2.1.4 release.
