### ISSUE TITLE
Twitter uploads fail

### ISSUE THREAD

**Issue by arnoudkooi** [Gifox/Tracker#145]
Uploading gifox to Twitter always fails, this is my main usecase...

**Comment by arnoudkooi** [comment]
Just found that its i can get the details of the error when viewing cosole.
A resize option would be nice! :)

![image](https://user-images.githubusercontent.com/840781/78923360-610bc380-7a98-11ea-9ad9-d28bacb8c171.png)

**Comment by ianbytchek** [comment]
Oh, that's new! We saw a few issues with Twitter lately and I don't think it would show any error details before, hence was all the confusion. Thanks for sharing! 👍

> A resize option would be nice! :)

I'm guessing you're referring to Twitter, but just in case, you can do that with Gifox. In fact, you can set it to resize to fit 2048x2048 sharp!

<img width="488" alt="image" src="https://user-images.githubusercontent.com/1086845/78926683-61ef2600-7a95-11ea-9b86-af7f17e9ee3d.png">

**Comment by arnoudkooi** [comment]
Cool, I was referring to Gifox. This is great for reducing file size!

**Comment by ianbytchek** [comment]
Technically this is to reduce the image size, which directly related to file size. If you want to get the most out of it I can recommend giving this a quick read: https://medium.com/gifox/mastering-high-quality-gifs-with-gifox-e08647cd5b3b

**Comment by arnoudkooi** [comment]
Nice, maybe a few "quick settings" to facilitate these would be nice for the novice user
