### ISSUE TITLE
No buttons visible?

### ISSUE THREAD

**Issue by martinf55** [Gifox/Tracker#146]
![image](https://user-images.githubusercontent.com/385521/78949217-e60bd280-7ac2-11ea-9b09-34851bfc85f5.png)

Hi, I can't see any buttons on the popup when I click the Gifox status bar icon?
High Sierra 10.13.6 (17G12034) on a MacBook Pro (15-inch, Late 2008).
Is this user error or a fixable issue or just due to ancient hardware?

**Comment by ianbytchek** [comment]
And that's when I thought I've seen everything that can possibly go wrong… 😂

Don't think this is any of your or hardware fault, but can't really think of any reason why it would happen, except for cases when the app gets damaged and can't load the icons. Can you share a little more details?

1. Was this okay before and turned up like this today or is this how it is right after install?
2. Is your app inside `/Applications` folder?
3. Are you using case sensitive file system?
4. What app version are you on? In not 2.1.3, can you get it from our website and give it a go?
5. Can you right or <kbd>Option</kbd> click on the status icon and click Support or Diagnostics Data to send app logs? They're likely to hold some clues.

**Comment by martinf55** [comment]
> And that's when I thought I've seen everything that can possibly go wrong… 😂

Yeah, sorry, it did have me confused until I realised there were supposed to be buttons! Probably a bit of an edge case though!

> 1. Was this okay before and turned up like this today or is this how it is right after install?

Right after install.

> 2. Is your app inside `/Applications` folder?

Yes.

> 3. Are you using case sensitive file system?

No, the usual case-insensitive, case-preserving MacOS default.

> 4. What app version are you on? In not 2.1.3, can you get it from our website and give it a go?

Yup, 2.1.3, just downloaded.

> 5. Can you right or Option click on the status icon and click Support or Diagnostics Data to send app logs? They're likely to hold some clues.

App Settings.txt:

```
SUEnableAutomaticChecks: 1
General.LaunchOnStartup: 0
SUHasLaunchedBefore: 1
NSNavLastRootDirectory: ~/Downloads
SULastCheckTime: 2020-04-10 11:59:19 +0000
General.OutputDirectory.Path: /Users/martin/Downloads
NSNavPanelExpandedSizeForOpenMode: {712, 448}
General.ShareCrashAndUsageData: 0
SUScheduledCheckInterval: 21600
UI.DidWelcome: 1
ThemeKitTheme: com.gifox.studio.DefaultTheme

```

Also, entries from the Console at Gifox.app startup:

```
default	12:59:17.029300 +0100	launchservicesd	CHECKIN:0x0-0x465465 98547 com.gifox.gifox2
error	12:59:17.169748 +0100	Gifox	        AEGetDescData of non-desc type 'reco' not a good idea
default	12:59:17.218886 +0100	Gifox	warning: no NSValueTransformer with class name 'NSSecureUnarchiveFromData' was found for attribute 'documentURL' on entity 'Media'
default	12:59:17.218981 +0100	Gifox	warning: no NSValueTransformer with class name 'NSSecureUnarchiveFromData' was found for attribute 'exportURL' on entity 'Media'
default	12:59:17.219107 +0100	Gifox	warning: no NSValueTransformer with class name 'NSSecureUnarchiveFromData' was found for attribute 'url' on entity 'Sharing'
default	12:59:17.345050 +0100	Gifox	UNIX error exception: 17
default	12:59:17.381182 +0100	Gifox	UNIX error exception: 17
default	12:59:17.390699 +0100	Gifox	UNIX error exception: 17
default	12:59:17.550394 +0100	kernel	AGC:: [Gifox pid:98547 mux-aware] starting, non-mux-aware app count 1 WS-ready 1 switch-state 8 IG FBs 3 EG FBs 3:3 power-state 0 3D idle HDA idle system-state 1 power-level 20:20 connect-change 1
default	12:59:18.287732 +0100	Gifox	Faulting in NSHTTPCookieStorage singleton
default	12:59:18.296104 +0100	Gifox	Faulting in CFHTTPCookieStorage singleton
default	12:59:18.298451 +0100	Gifox	Creating default cookie storage with process/bundle identifier
default	12:59:18.332167 +0100	Gifox	TIC Enabling TLS [1:0x604000167800]
default	12:59:18.333153 +0100	Gifox	TIC TCP Conn Start [1:0x604000167800]
default	12:59:18.337818 +0100	Gifox	Task <CAB72444-D00E-4B9D-B017-1A58D405A684>.<1> setting up Connection 1
default	12:59:18.338099 +0100	Gifox	[1 <private> <private>] start
default	12:59:18.811272 +0100	Gifox	TIC TLS Event [1:0x604000167800]: 1, Pending(0)
default	12:59:19.071949 +0100	Gifox	TIC TLS Trust Result [2:0x604000167b00]: 0
default	12:59:19.178884 +0100	Gifox	Task <CAB72444-D00E-4B9D-B017-1A58D405A684>.<1> received response, status 200 content K
default	12:59:19.181010 +0100	Gifox	Task <CAB72444-D00E-4B9D-B017-1A58D405A684>.<1> response ended
default	12:59:27.063231 +0100	Gifox	LSExceptions shared instance invalidated for timeout.
default	13:03:15.658286 +0100	Gifox	Establishing xpc connection to lsd
default	13:03:15.864295 +0100	Gifox	WiFi Platform capabilities 20000.
default	13:03:15.864358 +0100	Gifox	Device does not support AWDL
default	13:03:16.053163 +0100	Gifox	Read options: ffffffff80000001 -- URL: <private> -- purposeID: 4215E8D2-487D-4D20-9FA5-401E7F57AC5E -- claimID: 84AA5649-891A-49D8-92BB-6D3A556AD711
default	13:03:16.086534 +0100	Gifox	Claim 84AA5649-891A-49D8-92BB-6D3A556AD711 granted in client
default	13:03:16.086591 +0100	Gifox	Claim 84AA5649-891A-49D8-92BB-6D3A556AD711 invoked in client
default	13:05:03.932323 +0100	Gifox	LSExceptions shared instance invalidated for timeout.

```

**Comment by ianbytchek** [comment]
Thanks for all that! Can you also post (or [email](mailto://team@gifox.io)) your `App Logs.txt` from the Diagnostics Data – it would be more useful than what goes into Console.

You can also try getting the app from Mac App Store. Though the features are the same, one is sandboxed and the other isn't, resulting in macOS handling them slightly differently. In edge cases when the system encounters a glitch we recommend switching distributions, which, surprisingly, often helps. Still, very interested to learn what's causing this and how we can prevent it from happening, so, would much appreciate having a peak at your app logs! :)

**Comment by martinf55** [comment]
The `App Logs.txt` didn't appear for the downloaded version, so I installed from the App Store (still no icons :o( ) and this version did produce App Logs.txt:

```2020-04-10 22:32:11.538 [INFO] NEW SESSION!
2020-04-10 22:32:11.546 [INFO] Application v2.1.3 with Mac App Store distribution finished launching.
2020-04-10 22:32:11.546 [INFO] Application location: /Applications/Gifox.localized/Gifox.app
CoreData: warning: no NSValueTransformer with class name 'NSSecureUnarchiveFromData' was found for attribute 'documentURL' on entity 'Media'
CoreData: warning: no NSValueTransformer with class name 'NSSecureUnarchiveFromData' was found for attribute 'exportURL' on entity 'Media'
CoreData: warning: no NSValueTransformer with class name 'NSSecureUnarchiveFromData' was found for attribute 'url' on entity 'Sharing'
2020-04-10 22:32:11.611 [INFO] Core Data store was successfully set up at: /Users/martin/Library/Containers/com.gifox.gifox2-appstore/Data/Library/Application Support/Gifox 2/Main.sqlite
2020-04-10 22:32:11.611 [INFO] Setting up in-app purchase manager.
2020-04-10 22:32:11.619 [INFO] Attempting to update in-app purchase prices for [com.gifox.gifox2.pro, com.gifox.gifox2.pro.upgrade] product ids.
2020-04-10 22:32:12.116 [INFO] Registering ⌘⇧6 hotkey for toggle window selection in keyboard hotkey manager.
2020-04-10 22:32:12.118 [INFO] Registering ⌘⇧5 hotkey for toggle area selection in keyboard hotkey manager.
2020-04-10 22:32:12.119 [INFO] Registering ⌘⎋ hotkey for stop recording in keyboard hotkey manager.
2020-04-10 22:32:12.665 [INFO] Found 0 existing media library items.
2020-04-10 22:32:12.665 [INFO] Found 0 existing integrations.
2020-04-10 22:32:12.666 [INFO] Found 0 existing sharings.
2020-04-10 22:32:12.868 [INFO] Successfully retrieved in-app purchase product info for [com.gifox.gifox2.pro.upgrade, com.gifox.gifox2.pro] product ids.
2020-04-10 22:32:13.002 [INFO] Successfully updated in-app purchase £9.99 price for com.gifox.gifox2.pro.upgrade product.
2020-04-10 22:32:13.002 [INFO] Successfully updated in-app purchase £14.99 price for com.gifox.gifox2.pro product.
```

**Comment by ianbytchek** [comment]
We cleaned up the UI in the latest build and removed the long-forgotten hackarounds for macOS 10.12-10.13 where icon buttons would collapse and become invisible… 🤦‍♂️

Sorry for the troubles and massive thanks for pointing this out and providing the feedback. The hotfix update was just published and available for direct-download users. You can update by right-clicking on the status bar icon. App Store and Setapp updates are already in review and will be available shortly.
