### ISSUE TITLE
Varna?

### ISSUE THREAD

**Issue by krasimir** [Gifox/Tracker#148]
Hey,

not an issue with the app at all. It works pretty well actually. I'm wondering what "We (love) Varna" means. I'm living in a city called Varna so I'm curious.

P.S.
feel free to delete the issue if I'm breaking some rules.

**Comment by ianbytchek** [comment]
It means exactly what it says! We love everyone and every place around the world! 😉

**Comment by krasimir** [comment]
Oh, I see now :)
