### ISSUE TITLE
[Feature Request] Remember area selection

### ISSUE THREAD

**Issue by moofresh** [Gifox/Tracker#152]
I'm adding the same size images to a wiki - it'd be great if the area selection can remember the last-used dimensions.

**Comment by ianbytchek** [comment]
You can do that with lock aspect ratio – top-right button in the selection toolbox. When it's fixed, the selection will get restored the next time you start selecting an area.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/1086845/83010965-04954100-a011-11ea-9f17-933a37ad95f8.png">

**Comment by moofresh** [comment]
Aha, yes that does it, thanks.
