### ISSUE TITLE
[Feature request] Convert from mp4 to gif

### ISSUE THREAD

**Issue by danielgomezrico** [Gifox/Tracker#153]
Hi

I would love to have all of the converter features, like compression and resize, for a video that I recorded from another app.

In summary I have an mp4 video and I want to have it in gif

**Comment by ianbytchek** [comment]
The current beta comes with the initial video conversion support. If you're using direct download version, enable pre-releases and update the app to check it out. We're finishing a few touches and plan to make release this publicly in a couple of days.

**Comment by ianbytchek** [comment]
So, the latest 2.2.0 release is capable of doing that. Can we close this?

**Comment by danielgomezrico** [comment]
AWESOME THANKS
