### ISSUE TITLE
Gifox stopped recording keyboard interactions

### ISSUE THREAD

**Issue by oleq** [Gifox/Tracker#154]
All permissions are granted (also tried revoking and granting accessibility permissions manually) and the settings are like below

![](https://user-images.githubusercontent.com/1099479/83633340-1773bc80-a5a1-11ea-950e-e73711ef6cf8.png)

but no keystrokes are recorded in the GIF.

---

Catalina 10.15.5.

Gifox 2.1.4 00

**Comment by ianbytchek** [comment]
Interesting. Does it record mouse interactions? It might be some other app consuming the events, but if it's been working before and not working any more it's odd. Can you restart the Mac as it solves 99.9% problems, checking permissions once more and try again? Also try closing other apps, especially any tools or services, which might rely on keyboard input. Please share what you find?

**Comment by oleq** [comment]
Yesterday I tried rebooting and it didn't help. The app did record mouse actions, though. 

Then I updated the system to https://support.apple.com/en-us/HT211215 and surprise, surprise, keyboard interactions are recorded properly (bugfoots... ❤️). Honestly, I'm not sure what caused the problem and what fixed it. It could be as you said: some application intercepting the events. But which one? Who knows? 

I'm gonna watch this thing over the next couple of days and I'll let you know when the problem is back. 

Thanks!

**Comment by ianbytchek** [comment]
Very interesting! Yes please, if you have any thoughts on what might causing it any hints would be much appreciated! 👍

**Comment by eccentric-j** [comment]
I am running into this myself. About a month ago I needed to record my screen and disabled keyboard interactions so it wouldn't reveal my password when logging in. Today I tried to turn keyboard interactions back on and for whatever reason they do not appear in the recordings.

Only option I tried was restarting gifox. Anyone run into this since then?

**Comment by iby** [comment]
@eccentric-j did you try re-enabling (or better removing, restarting, and adding again) Gifox in system Security & Privacy →  Accessibility System Preferences?

![image](https://user-images.githubusercontent.com/1086845/222554566-66d177a8-bda1-454b-baa1-f45264979bdb.png)

**Comment by eccentric-j** [comment]
Just tried that. It seems to have done the trick. Thanks!
