### ISSUE TITLE
Feature request: Compression independent of recording settings

### ISSUE THREAD

**Issue by adam-zethraeus** [Gifox/Tracker#155]
It would be excellent to have top notch compression options in the edit GUI. 

If a local implementation is not viable:

Many excellent open source solutions are GLP2, and so difficult to ship—but not difficult to detect and use if available, or allow as use for configuration.

e.g. https://github.com/kohler/gifsicle

**Comment by ianbytchek** [comment]
I feel I'm missing a point here. Gifox offers a complete range of export and compression options you might need to fine-tune your GIFs. Is this a question of adding more options or is there a problem with the output quality? Please elaborate.

FYI: We have a pretty good article on this subject: [Mastering High Quality GIFs with Gifox](https://medium.com/gifox/mastering-high-quality-gifs-with-gifox-e08647cd5b3b), you might be interested in checking it out! 🙂

**Comment by ianbytchek** [comment]
@zethraeus Can you elaborate? 🙂

**Comment by adam-zethraeus** [comment]
@ianbytchek oh, sorry! I just meant that being able to compress post-recording, without changing the recording settings would be nice!

<img width="472" alt="image" src="https://user-images.githubusercontent.com/509838/89128365-13352400-d4aa-11ea-8f5c-979a317605eb.png">

On reflection it looks like you can do this here without altering global defaults, but presets that are marked relative to their impact on file size would be nice!

**Comment by ianbytchek** [comment]
Yes, this is exactly where you do that. We continue working on the better UI step by step, so things will eventually get smoother and clearer. This particular feature is tracked in #44 and #37. Unfortunately it's a pretty challenging job and we're sorting out other more pressing issues right now. But will get to it sooner or later.
