### ISSUE TITLE
Mis-timed mouse clicks

### ISSUE THREAD

**Issue by petergodden** [Gifox/Tracker#160]
After using Gifox to make gifs for a while it starts to record the clicks at the wrong time as you can see in the gif below:

![2020-06-24 14 47 10](https://user-images.githubusercontent.com/8982583/85502103-fd6e4c80-b629-11ea-91ce-d53780638f70.gif)

I end up having to quit and restart to get it to work again. It was actually difficult to figure out how to quit also. 

Using:
MacOS Catlina 10.15.5
Processor 2.4ghz 8-core intel core i9
Memory 32 gb 2667 Mhz ddr4

**Comment by ianbytchek** [comment]
Hey Peter, apologies for the lagged response – I started looking into this but got carried away… I thought it might be performance-related, but doubt that it could be the reason on hi-end spec like yours. Are you using the latest >2.2 Gifox version? Does it happen all the time or in some situations? Can you also test keyboard typing, i.e., enable keyboard input capture and try typing something in a text field along with mouse clicks to see if that's lagging too?

**Comment by petergodden** [comment]
No problems at all. 

Yes, I'm on version 2.2.1 00

<img width="485" alt="About" src="https://user-images.githubusercontent.com/8982583/86737093-59e45980-c077-11ea-8446-7b0a10da54d5.png">

It doesn't happen all the time. It seems to be quite random when it kicks in so far. The only thing I can say with certainty is that after a random period of time of use between 10 minutes, all the way out to a few days, it starts to mistime. 

It more seems to be with the number of gifs I create, once I've made over 10 in one session the likely hood of the lag seems to go up. 

Once it starts mistiming it continues doing it until restart. 

Another thing I noticed is that after a few videos of mistiming, it starts to cut the videos much shorter than I recorded for. 

Unfortunately, I was not able to test if the keyboard capture lags along with the clicks because turning it on does not seem to work. Originally it was capturing keyboard interactions but I turned it off a week ago. Since then I can't get it to work again. I restarted the app and even though it says to capture keyboard interactions, that doesn't seem to happen.

![2020-07-07 17 43 11](https://user-images.githubusercontent.com/8982583/86740499-0aebf380-c07a-11ea-9333-b7fc7398706c.gif) I know that should probably be a separate issue, but its not a biggy for me. Just including the gif so you know I'm not crazy ;-)

**Comment by ianbytchek** [comment]
Wow, Gifox is seriously crippled for you… ☹️ Sorry! Okay, I'll see into this further at my end. In the meantime, if you spot any odd behaviour, including what's already listed above, can you please send me diagnostics data from the app's menu to include app logs – they often contain clues that help figure out what's wrong. Also:

1. After using the app for awhile and when this starts happening, in Activity Monitor, can you check what's Gifox's CPU and memory usage are? (Should really add this into diagnostic data…)
2. For the keystrokes issue, before I create a separate one, can you quit the app, [remove it from the Accessibility Control Privacy Preferences](https://user-images.githubusercontent.com/1086845/86766984-330c3000-c043-11ea-8601-c01b2fbbd981.gif), add it manually again, and give it another go? For a moment I thought it might be the issue with TextEdit, but tested all distributions locally and it seems working. Most likely this is a glitch with accessibility access, but might be some other app or service stealing the keyboard events. In any case, let's start with the quick checks.

Another issue I know of and working on is when creating large recordings, including full screen on any retina display. The larger the graphic size the more resources we need to process it – this may lead to a higher frame-drop rate when things are not catching up in time and result in the final recording looking laggy. In theory this can be related to a mistiming as the drawn interactions are laid over the actual capture. I'll also look into this deeper in case something is missing there.

**Comment by petergodden** [comment]
Heya, yeah CPU usage seems to go off the chart for the first 5 seconds of starting a recording. Then it goes down to about 70-90% 

<img width="1049" alt="Screenshot_15_7_20__1_39_pm" src="https://user-images.githubusercontent.com/8982583/87500847-ee1a7600-c6a0-11ea-8eaf-a9da0c8d74fa.png">

I've also attached the settings and event logs: 

[App Settings copy.txt](https://github.com/Gifox/Tracker/files/4922768/App.Settings.copy.txt)

[App Logs copy.txt](https://github.com/Gifox/Tracker/files/4922767/App.Logs.copy.txt)

**Comment by iby** [comment]
Hey @petergodden, it's been awhile! I'm tidying up some old issues, wanted to let you know that we just released v2.4.2 that addresses a lot of issues with recording and processing. It includes a fix for a very similar issue with mis-clicks and recording should be much more stable now.

Could you give it a go and let me know if anything odd like that is still happening? I'm going to close this down, but feel free to reopen if there are still any issues! 🤞
