### ISSUE TITLE
Mac key stops working every time I start Gifox 

### ISSUE THREAD

**Issue by ayaya459** [Gifox/Tracker#161]
I've been really enjoying using Gifox, it's great!
Recently, every time I start Gifox, my Mac key "a" stops working for some reason. I can't remember changing the keyboard settings and it might be interfering with another app but cannot figure out with what. Is there a way to check this? 
Any advice would be greatly appreciated!

**Comment by ianbytchek** [comment]
Hey Aya! That sounds worrying, would be great if you can look further into this, so if there's a problem we fix it. Gifox uses only a few keys. It uses <kbd>Cmd</kbd>+<kbd>A</kbd>, but it's activated only during active selection, not <kbd>A</kbd> on its own. Can you confirm if it's just <kbd>A</kbd> or <kbd>Cmd</kbd>+<kbd>A</kbd>? You can verify if it's the problem with the app by quitting it – once you do all key bindings are released. A user had a problem with setting a custom shortcut and forgetting about it, he used the [ShortcutDetective](http://www.irradiatedsoftware.com/labs) app, it's half way through the page. You can also try that too.

**Comment by ianbytchek** [comment]
Did you have a chance to look into this and find out what caused it? :)

**Comment by ianbytchek** [comment]
Just received another similar reports with more info. This indeed happens and needs further investigation.

**Comment by ayaya459** [comment]
Hi Ian, sorry I hadn't responded since my previous post. I did some further digging but recently I had stopped experiencing this issue which is great but also made it difficult for me to recreate the issue and further investigate. I'll keep you posted if I find anything useful though!

**Comment by ianbytchek** [comment]
Figured out what's wrong, the fix is under way. This happens once you've cleared the shortcuts completely, instead of ignoring them the app registers the "empty" value shortcut, with coincides to be letter A on the regular keyboard. For now, to prevent this from happening simply restore shortcuts to their defaults or if you don't need them just set some non-empty key combinations until the next update. Sorry for the troubles! ✌️
