### ISSUE TITLE
Confirm that GIFs are not uploaded unless user chooses

### ISSUE THREAD

**Issue by wearhere** [Gifox/Tracker#162]
Hello, my company would like to ensure that my GIFs are not processed by cloud services nor uploaded to cloud services. Can you confirm that the Mac app processes and stores GIFs locally unless I explicitly enable the upload functionality?

**Comment by ianbytchek** [comment]
That's correct. All recording, processing and exporting is done locally – Gifox doesn't rely on anything from the outside. GIFs can be uploaded directly to connected services only if you chose to do so manually. The only network activity the app gets involved in is when verifying the license and sending anonymized crash and diagnostics data to Microsoft's [App Center](https://appcenter.ms). The latter can be disabled in general preferences, but we very appreciate if you keep it enabled – this service helps us to understand who's having what issues on what macOS versions and allows to respond to these problems more efficiently without waiting until users get in touch and provide step-by-step reproduction instructions. ✌️

**Comment by wearhere** [comment]
Great, thanks!
