### ISSUE TITLE
Selection area should be removed from final gif

### ISSUE THREAD

**Issue by forgng** [Gifox/Tracker#166]
The final gif show briefly flash the selection area border

![2020-07-16 21 30 15](https://user-images.githubusercontent.com/4640127/87714993-efd16000-c7ac-11ea-86b6-b01de242e4e3.gif)

**Comment by ianbytchek** [comment]
Thanks for reporting this. We expect this and similar issues with cursor fixed in the next release. Stay tuned!

**Comment by ianbytchek** [comment]
This should be fixed in the final release. Please reopen if discover something out of line? 👍
