### ISSUE TITLE
Stops Recording after a few seconds

### ISSUE THREAD

**Issue by MSAdministrator** [Gifox/Tracker#167]
I am on a 2018 Macbook Pro with i7 and 16GB of ram.

Gifox continually (event after resetting defaults) stops recording a GIF after about 10 seconds.  The only thing I think of that is different is that I am using a Dell 49" widescreen but I am not recording the entire screen just a small portion of it.  

Not sure what data you need to help troubleshoot but it's basically useless at this point.

Thanks for any help! Love the product BTW

**Comment by ianbytchek** [comment]
Hey Josh! Thanks for compliments! Gifox would stop recording itself after 10 s only in a free version. It would also add a small foxy watermark. These are the limitations of the free version.

We had some complaints about this not being very obvious in the original Gifox 1 version, but reworked and improved this in version 2 – not sure which version you're on. If you're using the paid version (Gifox Pro) and still getting this please let me know?

**Comment by ianbytchek** [comment]
I'm wondering if you had this figured out?

**Comment by MSAdministrator** [comment]
Yeah, thanks!  I realized I hadn't signed in to the appstore under the account which I bought it.  Thanks again!
