### ISSUE TITLE
It takes forever to render

### ISSUE THREAD

**Issue by pry0cc** [Gifox/Tracker#168]
I'm leaving this comment mainly because the interface has bugged me so much to leave feedback, so this is my feedback.

It takes forever to render a short sequence, and when it does generate it, the filesize is huge!

**Comment by ianbytchek** [comment]
Is your "short sequence" by any chance 15+ fps full screen retina video?

**Comment by ianbytchek** [comment]
Putting the sarcasm away, if you have a real question or want any details feel free to reach out – I'm here to help. [This](https://medium.com/gifox/mastering-high-quality-gifs-with-gifox-e08647cd5b3b) is a good starting point on finding good balance between file size and quality.
