### ISSUE TITLE
Delay start of recording

### ISSUE THREAD

**Issue by austenc** [Gifox/Tracker#170]
There should be a setting or hotkey to delay the start of the recording (after you hit record) by a few seconds. In my case, 3-5 seconds would be fine. This helps to avoid two issues:

- "Dead space" at the beginning of the recording while I click into another window
- Having to edit the recording to make it perfect. 

Having a few extra seconds... a countdown like 3...2....1.... would be really useful for making single-take clips. I used to use licecap and it was one of the best features. Is this something that could be added to the preferences? A box where you can type in the number of "count down" seconds would be great!

I found an older issue on this, but the proposed solution wasn't very helpful. https://github.com/Gifox/Tracker/issues/70

**Comment by iby** [comment]
@austenc I'm doing some old issue housekeeping. Wanted to let know that basic support for this was added a few releases ago and can be configured in [Capture Preferences](https://gifox.app/docs/using-gifox#preferences-window). I'm going to close this down.
