### ISSUE TITLE
First frame shows crop box edges

### ISSUE THREAD

**Issue by peppy** [Gifox/Tracker#171]
Notice the circles on the edge of the first frame:

![2020-09-08 12 26 14](https://user-images.githubusercontent.com/191335/92430063-bc201e80-f1ce-11ea-9ef5-8107aa604e7e.gif)

I don't believe this was always an issue, but has been happening for the last few releases at least.

**Comment by ianbytchek** [comment]
Can you confirm what Gifox version are you using? We resolved #166 a few versions back and I'd be really surprised to see this happening again… :)

**Comment by peppy** [comment]
I just updated today to the newest release (`Gifox 2.2.4-beta.0 is currently the newest version available.`).

**Comment by ianbytchek** [comment]
Hmmm, I will look into this, thank you for reporting! Can you confirm what macOS are you on by any chance?

**Comment by peppy** [comment]
I am on macOS 10.15.6, non-retina display (2560x1440 + 1080x1920 second display, menu bar, dock hidden). I'm triggering capture using a keyboard shortcut, then dragging capture area, then hitting the red record button.

Not running anything too crazy which I could imagine causing such issues.

**Comment by unstubbable** [comment]
I also noticed this.

**Comment by iby** [comment]
Hello friends. I'm tidying up some old issues here. I believe this should've been fixed a few releases ago. I'm gonna close this down, if you notice anything odd still happening with this, please report and re-open! 🙏
