### ISSUE TITLE
Request: Surface the composition mov files

### ISSUE THREAD

**Issue by isaacbowen** [Gifox/Tracker#172]
I love, love, _love_ the way that Gifox annotates captures with keyboard and pointer activity. For the work that I'm doing, it's often easier to just share the mov file, rather than waiting for a gif. In some cases, the mov is preferable anyway.

To that end, I ended up adding ~/Application Support/Gifox 2/Compositions to my Finder favorites, so I can easily snag a mov after recording is done.

Can we have an easy, app-facilitated way to fetch those files? :)

**Comment by ianbytchek** [comment]
Hey @isaacbowen, sorry for the lagged reply. Yes, we plan to add the ability to export raw files but at the moment prioritizing on other more important improvements. Will post any updates on this here. 👍

**Comment by iby** [comment]
I'm tidying up some old issues. You might have seen this already, with 2.4.0 release there's support to export MP4 (H.264) and MOV (ProRes 422) video from the composition – where you re-export the GIF.

![CleanShot 2022-06-18 at 08 47 53](https://user-images.githubusercontent.com/1086845/174428441-6c789c78-e95e-42a6-9ef7-d8e33fff4a9e.png)

I think that should work for what you're looking for, just make sure to adjust FPS before export – you probably don't want to end up with a 10 FPS MOV… 😅

But I also realized that it might be handy for some people to be able to get the original RAW, so we're going to add this support too in one of the upcoming releases.

I'm going to close this down. If you feel there's anything is missing of have more feedback, please feel free to re-open! 👍

**Comment by isaacbowen** [comment]
@iby This is fantastic. Thank you. :) :)

**Comment by isaacbowen** [comment]
@iby Hey, the way you're surfacing this feature now is _awesome_. I use it all the time. Thank you, thank you, thank you. :)

<img width="566" alt="Screenshot 2023-09-01 at 11 01 29 AM" src="https://github.com/Gifox/Tracker/assets/302012/5cfbf2a5-2612-4a81-b4cc-1373906b6650">
