### ISSUE TITLE
Update failing to encode

### ISSUE THREAD

**Issue by gilbox** [Gifox/Tracker#175]
Just got the latest version and now I get the dreaded "Something went wrong...".  It seems to happen on every capture whether window or selection. Tried restarting app and restarting computer.

v2.2.4 02

**Comment by ianbytchek** [comment]
Hey @gilbox, sorry for the troubles. If you're using the direct-download version please check for updates, the fresh build addresses this and a few other issues. If you're using Setapp version we expect the new release to be approved shortly.

**Comment by monkeypox8** [comment]
I was running into the same issue after updating this morning. Downloading from the site and reinstalling fixed it for me.

**Comment by annunez** [comment]
I am using v2.2.4 03 and I am experiencing the same issue:
![image](https://user-images.githubusercontent.com/48221996/95612981-98a0fb80-0a3a-11eb-921e-20e7c1905561.png)

**Comment by gilbox** [comment]
I installed the update 2.2.4 03. Now the `"Something went wrong..."` show up for me, but it still doesn't work.

**Comment by monkeypox8** [comment]
> I installed the update 2.2.4 03. Now the `"Something went wrong..."` doesn't show up for me, but it still doesn't work. A file is created, but it's not animated. It's just the first frame.

Yeah, seeing the same result here. I thought it was working, but the GIF being generated doesn't animate. Opening the file with different programs, browsers, etc. has the same result.

**Comment by quicksnap** [comment]
Same--2.2.4 03 has the same issues for me.

**Comment by ianbytchek** [comment]
Yep, something is screwed up and it's not very clear what exactly. I just reverted everything to 2.2.3, please get it from the [website](https://gifox.io) and I'll try to figure out the cause of this over the weekend. If you can send your diagnostics data (bottom right button) it would be very helpful. Again, apologies for the troubles… 🤦‍♂️

**Comment by annunez** [comment]
@ianbytchek There you go. Thanks for the update.
[Diagnostic Data.zip](https://github.com/Gifox/Tracker/files/5356610/Diagnostic.Data.zip)

**Comment by bheptin** [comment]
> Yep, something is screwed up and it's not very clear what exactly. I just reverted everything to 2.2.3, please get it from the [website](https://gifox.io) and I'll try to figure out the cause of this over the weekend. If you can send your diagnostics data (bottom right button) it would be very helpful. Again, apologies for the troubles… 🤦‍♂️

unable to get 2.2.3 from the site. please advise.

**Comment by ianbytchek** [comment]
This must be the web-cache thing, thought it gets cleared with every release. Please use a private browser session or the [direct-download link](https://distribution-absf.s3.eu-central-1.amazonaws.com/gifox/020203.00.dmg).

**Comment by quicksnap** [comment]
Reverting works! @ianbytchek Thanks for your work on this. Many people at my job love this product!

![2020-10-09 12 42 36](https://user-images.githubusercontent.com/1199742/95625179-f29ac480-0a2c-11eb-8863-1d7a9d542c7d.gif)

**Comment by gilbox** [comment]
BTW, the UI in the list was also a little janky compared to 2.2.3 ... the jankiness occurred when I hovered over list items. The UI elements would sort of twitch around

**Comment by ianbytchek** [comment]
@gilbox Realizing that this will come up in later conversations I've created a separate #177 issue for that. Would love to know your feedback on this.

**Comment by ianbytchek** [comment]
See https://github.com/Gifox/Tracker/issues/159#issuecomment-707207993 for details.
