### ISSUE TITLE
Failing to render gifs even through system restart

### ISSUE THREAD

**Issue by ltetreault-va** [Gifox/Tracker#176]
All gifs fail to render after the recording is finished, this happens even after a full system restart.

[App Logs.txt](https://github.com/Gifox/Tracker/files/5356623/App.Logs.txt)
[App Settings.txt](https://github.com/Gifox/Tracker/files/5356624/App.Settings.txt)

**Comment by ianbytchek** [comment]
Hey @ltetreault-va, sorry for the troubles. Please see https://github.com/Gifox/Tracker/issues/175#issuecomment-706313922 for details.

**Comment by ltetreault-va** [comment]
Oops looks like this is a duplicate of #175

**Comment by ianbytchek** [comment]
No worries!
