### ISSUE TITLE
New library list UI/X feedback

### ISSUE THREAD

**Issue by iby** [Gifox/Tracker#177]
We have been experimenting with the responsive library item UI in attempt to find an optimal way to allow renaming GIFs before (and after) they are ready.

The end goal is to allow renaming the item and accessing the toolset without extra mouse clicks – we want to keep everything as simple as possible. 

The challenge with that is we can't show the button toolset on mouse roll-over as the title text field disappears. Instead we want to have different active areas to support gestures for renaming and gestures for showing the toolset. As it's not obvious straight away where these areas are we've implemented the reactive shift effect that informs users about the interactivity.

<img width="300" src="https://user-images.githubusercontent.com/1086845/95647247-00a91d80-0adf-11eb-981e-29f573213728.gif">

Overall this feels like a good idea but we know that some people hate such UI animations and perhaps the implementation can be improved. We'd love to hear your feedback and thoughts on this.

**Comment by gilbox** [comment]
After the initial confusion about this in the previous buggy version, I really like this feature. The animation could be a little smoother perhaps? Or maybe the thumbnail shouldn't move at all. There's not too much to complain about tbh.

**Comment by chriscalo** [comment]
If you're still curious, I find this part of the UI rather off-putting. The way the row wiggles as I move my mouse feels unstable and too clever.

My 2¢:
- make each row taller if necessary for things to fit (see below)
- always show the filename in the top portion of the row
- move the date to the top-right corner of the row (right of the filename)
- while the GIF is generating, show the progress bar in the bottom portion of the row
- after the GIF is done generating, always show the icon buttons in the bottom portion of the row
