### ISSUE TITLE
Feature Request: Processing Indication in Menu Bar Icon

### ISSUE THREAD

**Issue by brycekunkel** [Gifox/Tracker#179]
I think it'd be super cool if the app icon could indicate that a recording is currently processing. Since part of the file is written to the destination before processing is complete, I've occasionally made the mistake of attaching an incomplete GIF to an email. It'd be great to know that the GIF isn't done yet with a quick glance at the menu bar.

**Comment by iby** [comment]
Thank you for reporting this. I'm tidying up some old tickets and gonna close this one in favor of https://github.com/Gifox/Tracker/issues/183.
