### ISSUE TITLE
Clearer and more intuitive recording user interface

### ISSUE THREAD

**Issue by ianbytchek** [Gifox/Tracker#18]
- [x] Shortcut to start recording when selection is already made – you can use `Spacebar` to do that, this should be made intuitive from the ui.
- [x] Adjustable recording tools / buttons – they should never go off the screen when making the selection.
- [x] Preconfigure compression and other preference per-recording.
- [ ] Ability to set sharing services before recording begins.

**Comment by dimitrieh** [comment]
please see this comment: https://github.com/gifox/tracker/issues/5#issuecomment-242155924

**Comment by ianbytchek** [comment]
Sharing is a little different story, gonna close this down to avoid cluttering.
