### ISSUE TITLE
Colours not quite right in gif

### ISSUE THREAD

**Issue by joseffsmith** [Gifox/Tracker#184]
This is the gif I've recorded
![2020-12-21 11 46 58](https://user-images.githubusercontent.com/26124821/102775501-e3b58400-4384-11eb-96ee-08676077c8a8.gif)

Using these settings
<img width="576" alt="Screenshot 2020-12-21 at 12 01 23" src="https://user-images.githubusercontent.com/26124821/102775546-f92aae00-4384-11eb-8002-99e05be1ace8.png">

On this version
<img width="494" alt="Screenshot 2020-12-21 at 12 01 37" src="https://user-images.githubusercontent.com/26124821/102775553-fd56cb80-4384-11eb-9f5e-58edaca22cca.png">

With this os version - 
<img width="587" alt="Screenshot 2020-12-21 at 15 23 54" src="https://user-images.githubusercontent.com/26124821/102792638-b080ee00-43a0-11eb-82f3-ee755f3e4042.png">

Compared with this screenshot taken with the mac system screenshot tool, you can see that the colours are a bit "washed out" or just not correct.
<img width="1237" alt="Screenshot 2020-12-21 at 12 01 04" src="https://user-images.githubusercontent.com/26124821/102775665-368f3b80-4385-11eb-9904-6c0c8a239fa4.png">

(It's easier to compare when opening the two files in chrome and flicking between tabs)

Is there a setting that I'm missing that will help in this case or is there something I'm doing incorrectly?

I hope this is enough info for you to see the issue but please let me know if there's anything else I can add.

Thanks in advance

**Comment by elliotttn** [comment]
Hey guys,

Just wanted to bump this as I noticed the same issue today as well.

I'm using Gifox version 2.2.5 01, on an iMac OSX Catalina 10.15.5 - not sure if has any relation to this being a retina display machine?

Took a screenshot of two GIFs side by side - left is a GIF made in LICEcap, right is a GIF made in Gifox, has the same "muted" colours as Joseff was getting:

<img width="630" alt="Screenshot 2021-01-20 at 10 28 12" src="https://user-images.githubusercontent.com/31101503/105162235-3c09ae00-5b0a-11eb-8bc9-cdaf2bca5e64.png">

I know we can pick Max. colors but might need to be able to set the color profile used by Gifox?

**Comment by iby** [comment]
Hello friends, it's been awhile! :) Version 2.4.2 just landed and it should take care of all color issues. Could you please give it a go and let me know if there's anything odd is still going on?

I'm going to close this down, but please feel free to reopen if you notice anything worth commenting or have any other feedback! 🤞
