### ISSUE TITLE
After cropping/trimming the saved file has a size of 0 Bytes (seems damaged or not saved correctly)

### ISSUE THREAD

**Issue by axalandra** [Gifox/Tracker#187]
1. Record something (OK)
2. Open editor + crop it + "Done" (OK)
3. Progress runs for saving the cropped file (OK)
4. When opening the file via the Finder, the file size is indicated as 0 bytes, and the file can't be played (NOK); meanwhile, the same file can still be opened without issues in the Gifox editor (OK), but can't find a way to export it in a non-damaged way anymore (NOK); also copying the file from Gifox and pasting it somewhere else doesn't solve the issue (NOK)

![image](https://user-images.githubusercontent.com/9296010/105464716-46ef4a80-5c92-11eb-8122-a9f38591c1f7.png)

**Comment by iby** [comment]
From the tiny green check icon next to the name I'm assuming you're exporting to folder managed by Box or Dropbox or something similar? Can you confirm? Do I understand correctly that the initial export works fine?

In the past we had quite a few reports that exporting directly to such locations doesn't always work as expected resulting in crashes and corrupted files. Can you try changing the output folder location to any standard folder not managed by other apps/services and give it another go?

**Comment by iby** [comment]
Turned out to be an issue with OneDrive. Closing for now, still would be good to see if there's a workaround.

> The suggested fix with using a local folder rather than a cloud-based on helped. I used a folder in OneDrive, but switching it to a local folder solved the problem. Still weird that the error only occurs after cropping the recording, but the initial recording works without issues.
