### ISSUE TITLE
Return focus to previous app

### ISSUE THREAD

**Issue by timdmackey** [Gifox/Tracker#188]
When GiFox starts a screen recording, it should return focus to the previously open app. Currently, it doesn't return focus automatically, so when I'm recording clicks, it records an extra click as I click back into the application I record. Example:

![2021-01-24 10 55 18](https://user-images.githubusercontent.com/182772/105793060-4f1ee280-5f3d-11eb-91ed-9602e7488b55.gif)

**Comment by iby** [comment]
That's a very good issue! Gifox used to work exactly like you're describing, however, that would often cause problems with state updates being recorded and the captured apps looking flickery and funny during the first few frames. We worked around that by not stealing the focus at all in selection mode when triggered by a shortcut. 

After thinking about this I'm realizing that this won't work if you're creating a selection from the library popover – it needs the focus while open like any other app. We'll see how to improve that part but in the meanwhile you can use shortcuts to start the selection/recording to avoid that behavior.

**Comment by timdmackey** [comment]
Thanks for the feedback! You're right, I've been using the popover, I'll try using the shortcut from now on.

**Comment by iby** [comment]
Hi Tim, we've had a few reports and came up with a better solution which should work equally well for starting recording from the popover too. We're tracking this in https://github.com/Gifox/Tracker/issues/203, so I'm gonna close this down and will keep posted on progress there. Thanks again for reporting this! 👍
