### ISSUE TITLE
GIF turns bluish after editing

### ISSUE THREAD

**Issue by ramtinsoltani** [Gifox/Tracker#189]
After I finish editing a recorded GIF, the output's color profile changes and everything turns bluish. I tried recording with 'per-frame' and increasing the max colors all the way up to 265, also with  but nothing seems to work.

Original recording:
![2021-02-07 00 42 34](https://user-images.githubusercontent.com/7918069/107141427-78485700-68dd-11eb-92ee-2d0f1744a632.gif)

Edited recording:
![2021-02-07 00 42 34](https://user-images.githubusercontent.com/7918069/107141450-9f068d80-68dd-11eb-9172-0b749be70402.gif)

**Comment by ramtinsoltani** [comment]
I just tried another recording with fixed frame (so I don't have to edit the first seconds out) and the original recording is bluish too.

Seems like when the first frame is the terminal background (which has a blue tint) the rest of the recording adapts that color profile.

The recording looks correct in the editor's preview. Not sure why 'per-frame' color palette is not solving this.

**Comment by iby** [comment]
@ramtinsoltani Sorry for such a lagged reply. Hmmm, increasing the number of colors and going with per-frame palette would be my first suggestions, but from the looks of it it's reminds a color profile issue. Theoretically this may be happening on some screen configurations, but this is the first report I'd know of… 🤔

Is this happening on external or built-in monitor?

**Comment by ramtinsoltani** [comment]
@iby This is happening on an external monitor. Since when I opened this issue I have changed my Macbook to the new M1 chip.

I just recorded again from the original recording posted above and after editing the recording (cut some parts out in the timeline) the colors are different again (not bluish, but not correct). Take a look:

![2021-06-02 11 15 05](https://user-images.githubusercontent.com/7918069/120532337-7296e580-c394-11eb-871e-6849ee0dd7d5.gif)

**Comment by iby** [comment]
@ramtinsoltani it's been awhile! :) Version 2.4.2 just landed and it should take care of all color issues. Could you please give it a go and let me know if there's anything odd is still going on?

I'm going to close this down, but please feel free to reopen if you notice anything worth commenting or have any other feedback! 🤞
