### ISSUE TITLE
No indication that the gif is being generated

### ISSUE THREAD

**Issue by Kreshnik** [gifox/tracker#19]
After stopping the recording, it would be nice to have an indicator that the gif file is being processed and saved. Currently, you do not have any indication that the process was successful, you see an empty list until a preview pops up.

**Comment by ianbytchek** [comment]
Confirm that this happens when the first recording (there are no other recordings) is being processed. Judging by `you see an empty list until a preview pops up` I assume you are talking about the same thing?

**Comment by Kreshnik** [comment]
Yes.
