### ISSUE TITLE
Gif is choppy

### ISSUE THREAD

**Issue by wmccrery** [Gifox/Tracker#190]
I've recorded a couple second long gif and the recording hangs right in the middle, then skips to the end. Tried multiple times.
![2021-02-26 14 09 08](https://user-images.githubusercontent.com/13002770/109356568-23459400-783e-11eb-935c-7946786ff7ac.gif)
![2021-02-26 14 14 16](https://user-images.githubusercontent.com/13002770/109356578-25a7ee00-783e-11eb-9bb6-50529a74c6e4.gif)

**Comment by tyirvine** [comment]
<img width="692" alt="Screen Shot 2021-03-08 at 5 34 03 PM" src="https://user-images.githubusercontent.com/39813066/110400220-7dabd500-8034-11eb-87d2-5693785c0a9f.png">

Did you set `Repeat pause` to 0s?

**Comment by iby** [comment]
@wmccrery Apologies for the lagged response, this completely slipped through my fingers. Hmm, this is interesting, considering everything runs smoothly at the start. Does it play the same if you open it in the editor?

**Comment by iby** [comment]
Friends, we just released v2.4.2 which addresses A LOT of issues with recording and processing. Please give it a go and do let us know if there are any troubles at all. I'm going to close this down in the meantime, but please let me know if this (or anything else odd) is happening – we'd want to know about it! 🙏
