### ISSUE TITLE
Unable to put a created gif in the Gifox app

### ISSUE THREAD

**Issue by srishmatta** [Gifox/Tracker#192]
I can't see any option to put in my existing gif in the app. I want to edit my gif. The GIF I have was also created through Gifox on another laptop and shared with me later. I am trying to put it through the Drag & Drop Video-GIF feature, but this is not working, neither it's giving me any feedback. 
![image](https://user-images.githubusercontent.com/8349668/113123132-ed773f00-9231-11eb-8b59-5d0abba24add.png)

**Comment by iby** [comment]
Apologies for the lagged reply. Yes, we don't support this yet, only videos, but this is coming up shortly along with more formats support.

**Comment by iby** [comment]
It's now possible to import GIFs created externally. Please give it a try! 👍
