### ISSUE TITLE
Error : embeded in the html with img tag

### ISSUE THREAD

**Issue by Wizzen2801** [Gifox/Tracker#195]
Hello,

It is well functioning to import movie files and to export gif files.
I have tried to embed it in the html with img tag but it did not work.

Is there anybody who can tell me how to resolve this issue?
Thanks.

**Comment by iby** [comment]
There are a few examples in our issues with attached GIFs, like [here](https://github.com/Gifox/Tracker/issues/182) or [here](https://github.com/Gifox/Tracker/issues/173#issuecomment-759508996) – all using standard `<img>` tag to embed the image.

You can verify that the GIF itself is in healthy shape by just dragging it onto the browser to open it in a new tab – if it plays then everything should work as expected.

Another thing to keep in mind is the size of your GIFs, which may turn out to be too big and take a long time to load. Finally, if you're embedding it indirectly, i.e., uploading to Twitter or other website, it may have certain limitations or optimizations, so it's better to check with them.
