### ISSUE TITLE
Gifox 1.6.1 03 Crashes in macOS 11.4 when hovering over a window

### ISSUE THREAD

**Issue by orcutt989** [Gifox/Tracker#196]
Title says it all. I just updated using the latest Gifox 1 on the website, but I'm still getting the same issue.  I submitted a support ticket with my system profile.

**Comment by iby** [comment]
Sorry for the lagged reply @orcutt989, this has completely slipped through fingers. You might want to see https://github.com/Gifox/Tracker/issues/115 for details and workarounds. Our primary focus is the current version improvements and ongoing development, and, unfortunately, version 1 won't be maintained in a longer run.
