### ISSUE TITLE
[Feature Request] Ability to change the color of the click dot

### ISSUE THREAD

**Issue by n8allen** [Gifox/Tracker#202]
Would like to have a setting in the preferences to choose a custom color for the click dot so it doesn't always have to be red.

**Comment by iby** [comment]
https://github.com/Gifox/Tracker/issues/156 and https://github.com/Gifox/Tracker/issues/157 are similar issues, it looks like you've already seen some of them. This is in the pipeline and hopefully coming this fall. We've been focused on other priorities lately. I will close this one in favor of those two, lets track progress and keep discussion there.
