### ISSUE TITLE
Default to last recorded area

### ISSUE THREAD

**Issue by chriscalo** [Gifox/Tracker#205]
- I tend to not get GIF recordings right the first time.
- And editing the GIF is too slow, so I just record it again.
- However, Gifox forces me to make the area selection again every. single. time.

Fix:
- instead of starting out in a no-selection state…
- start with the last-used area selection
- then users can just use the exact same area selection, …
- or adjust the area selection by dragging the handles, …
- or draw a new area selection box if they desire

**Comment by iby** [comment]
Hey @chriscalo, I believe you might be talking about https://github.com/Gifox/Tracker/issues/152#issuecomment-634585416 – check it out for the workaround!

**Comment by chriscalo** [comment]
Oh, that seems promising.

What's the downside to making that the default behavior? And why have the button at all? Who doesn't want it to work that way?

**Comment by iby** [comment]
You only need to do that once and the behavior is remembered until you turn it off. I wouldn't argue about preferences – there are as many as people in the room. Everyone uses their tools differently and we don't want to enforce any restrictions and ask users to change their habits without a strong cause, which this is not.
