### ISSUE TITLE
Copying and pasting GIF doesn't work

### ISSUE THREAD

**Issue by zsirfs** [Gifox/Tracker#206]
![image](https://user-images.githubusercontent.com/22249411/132185536-fcb261c3-c46f-45dc-835a-db7617b3f262.png)

How do you copy and export the file? The normal pasteboard cannot directly copy the gif, I don’t know if it can help me. thanks

**Comment by iby** [comment]
Pasting GIFs is handled differently by different apps, read more in https://github.com/Gifox/Tracker/issues/24#issuecomment-314402304. Dragging and dropping the recording thumbnail (or the actual GIF file in Finder, if you're using the original version of Gifox) works more predictably for that.
