### ISSUE TITLE
Bug - Multiple cursors appears in gif when cursor is "progress" on a web page

### ISSUE THREAD

**Issue by Ericlm** [Gifox/Tracker#208]
I tried to record a gif on a web page that uses at some point `cursor: progress;` to show that the content is being fetched. The issue is that when looking at the recorded gif, multiple progress cursors appears at the same time, and then things get back to normal when the `cursor: progress;` is removed.

I tried this on the [Bootstrap-vue skeleton component](https://bootstrap-vue.org/docs/components/skeleton) : 
![bug-progress-cursor](https://user-images.githubusercontent.com/19361503/134136645-990d7acb-e0a5-464f-8a4b-5cf85b6ae977.gif)

**Comment by iby** [comment]
Hey @Ericlm, very sorry for the laggy reply, this must have have slipped though my fingers. We had this issue on our backlog for some time and I just wanted to say that it was addressed and must be resolved in 2.4.x versions. It's already available in direct-download and Setapp versions. Mac App Store version will be released today or tomorrow once reviewed by Apple.

Again, apologies for very bad communication. Please let me know if you run into any issues or have feedback! 🙏
