### ISSUE TITLE
Crash after buying Gifox :(

### ISSUE THREAD

**Issue by mochadwi** [Gifox/Tracker#209]
When trying to record exceed 19sec, crash occurred instead :(

**Comment by braxtonchristensen** [comment]
☝️ I am having the same issue; I just downloaded it today and restored my purchase; it crashes at the 19-second mark; no sharing enabled here.

**Comment by iby** [comment]
Sorry about the crappy experience folks. Can you share the app diagnostics data with us to include logs and configs, so I can look into this closer?

![2021-08-24 09 46 19](https://user-images.githubusercontent.com/1086845/163877914-7cb48ec2-61a1-4014-9072-b38aa216cfe5.gif)

**Comment by braxtonchristensen** [comment]
[App Logs.txt](https://github.com/Gifox/Tracker/files/8524898/App.Logs.txt)
[App Settings.txt](https://github.com/Gifox/Tracker/files/8524899/App.Settings.txt)
[System Info.txt](https://github.com/Gifox/Tracker/files/8524905/System.Info.txt)

**Comment by iby** [comment]
Hello friends, sorry for going off the radar. We finally released 2.4.2 yesterday which comes with many recording and processing improvements and fixes. Could you please give it a go and let me know if you run into anything similar?

Most of these issues are found to be hardware dependent and impossible to reproduce on our machines, so we mostly rely on your input. If there anything wrong, please send through the diagnostic data again (you can do it via in-app contact).

P.S. The Google Drive and Dropbox issues should also be resolved.
