### ISSUE TITLE
Gifs are recorded in reverse on retina screens

### ISSUE THREAD

**Issue by holleboom** [gifox/tracker#22]
Any idea how to fix this or is this just me?

**Comment by holleboom** [comment]
Ok setting the fps record/play settings to default fixes it.

**Comment by ianbytchek** [comment]
There was a similar disastrous issue #12 – was been fixed in 1.1.1. Are you using the latest 1.1.3? If so and if there's any info how you got it, besides above, or if it happens again and you can provide reproduction steps – that would be extremely helpful.
