### ISSUE TITLE
Mouse interactions are not in click locations

### ISSUE THREAD

**Issue by caseyparnis** [Gifox/Tracker#220]
I'm not sure if the duration of the gif matters, but after about 9 seconds the red dot mouse interactions are about an inch off from where the click actually was. This happens whether the window I'm making the gif of is set to 0% zoom, 10% zoomed in, or 10% zoomed out.
![2022-02-11 16 16 25](https://user-images.githubusercontent.com/17502366/153687834-bdf3a25c-6e54-40c5-a982-53aab6dc78bd.gif)
.

**Comment by iby** [comment]
Thanks for reporting this, very interesting – we had a similar issue a while back and I'm surprised that this resurfaces. It would be of great help if you can help reproducing it, so we know better what actually goes wrong behind the scenes:

1. Is it happening constantly? Can you locally reproduce it?
2. After it does, can you send the [diagnostics data](https://user-images.githubusercontent.com/1086845/155241437-ca9b437e-d2bb-4440-8ea1-a5ea0b8a12be.png) please?
3. From the attached GIF it doesn't seem anything of the following taking place, but can you think of anything like window resizing/moving, screen properties changing?

**Comment by caseyparnis** [comment]
Hi Ian, thanks for your help!

1. Yes, it happens constantly in Chrome, but sometimes only after a few accurate clicks. I tried to make a gif using the Numbers app and the clicks showed up correctly, so I would not be surprised if the problem was somehow Chrome specific.
2. Yes please see two new attached gifs and diagnostic data
3. In the first gif I attached I did not move the window at all or change any properties. In the past, I noticed that if I zoomed out on a window and then recorded a gif, then the clicks would be inaccurate. I stopped zooming out to solve the issue.

If you need any other information please let me know
[App Logs.txt](https://github.com/Gifox/Tracker/files/8121176/App.Logs.txt)
[App Settings.txt](https://github.com/Gifox/Tracker/files/8121177/App.Settings.txt)
[System Info.txt](https://github.com/Gifox/Tracker/files/8121178/System.Info.txt)

![2022-02-22 16 58 28](https://user-images.githubusercontent.com/17502366/155245570-224cafbc-2d29-4e44-8550-360604f20252.gif)
![2022-02-22 16 57 08](https://user-images.githubusercontent.com/17502366/155245577-0df6e97b-3fff-44b5-a81d-198841762ede.gif)
!

**Comment by iby** [comment]
Thanks Casey! I managed to catch this once while playing with the large Chrome window, will look further into this, hopefully this is something simple. Off the top of my head, if you try using free area selection (not window selection) this might behave better, give it a try if this is an option. P.S. you can quickly convert window into are selection with the shortcut (Cmd + Shift + 6 by default).

**Comment by caseyparnis** [comment]
Hey iby! I just wanted to let you know that your free area selection suggestion worked great. I prefer the look of the final gif with the entire window selected but it's not the end of the world. I'm still having this issue when I use the full window recording sadly. I'm attaching a new example gif and logs in case that helps, but I hope this is just a me issue haha.
[App Logs.txt](https://github.com/Gifox/Tracker/files/8836135/App.Logs.txt)
[App Settings.txt](https://github.com/Gifox/Tracker/files/8836136/App.Settings.txt)
[System Info.txt](https://github.com/Gifox/Tracker/files/8836137/System.Info.txt)
![2022-06-03 16 02 34](https://user-images.githubusercontent.com/17502366/171965411-2ef78abd-315a-4290-ad38-c298d693c28b.gif)

**Comment by iby** [comment]
@caseyparnis Hope you're well? Just wanted to let you know that this is resolved in latest 2.4.x releases. Apologies for it taking absolute ages – we really wanted to pack in some other fixes which took unexpectedly long time to comprehend and resolve. And thanks again for great reporting and examples. Your Chrome example helped to debug the issue – turned out the issue was with the window changing its name… 🤷‍♂️

And let us know if there are any issues or suggestions! 👍
