### ISSUE TITLE
Activated to Pro but still get "Upgrade to Gifox Pro" message

### ISSUE THREAD

**Issue by aplcreator** [Gifox/Tracker#221]
Hi,
I activated to Pro, but I still get the message on the app to "Upgrade to Gifox Pro".
I can do unlimited recordings but the Gifox watermark is still displayed on gif recordings and I cannot customize it.
I purchased the license directly from your website and downloaded the app (2.3.0) from your website as well.

Pls advise.
Thanks.

**Comment by RyanReadd** [comment]
We're also running into the same issue. 

And after clicking the "upgrade to pro" button get this message (have re-downloaded the app). 

![Screenshot 2022-02-14 at 10 21 32](https://user-images.githubusercontent.com/99650694/153845965-2fdac503-5e7f-4bdc-93c2-d58fc44ef807.png)

**Comment by aplcreator** [comment]
Yes. That's what I get too.
I downloaded the gifox app and installed it again... but no go.
Still get the same message.

**Comment by martin-braun** [comment]
I have the same problem. Please fix it. Also tried to re-download and re-install it without success. Thanks.

**Comment by iby** [comment]
Hey folks, a million apologies for this. Some of you also reached out via email and I already replied. In an attempt to make things better we've messed something up in one of the recent updates and it surfaced over this weekend resulting in broken Gifox Pro verification… 🤦

An update with a fix was just published, please update to the latest version to restore your Gifox Pro access. You can also just grab the latest copy from our website – don't forget to quit the currently running app and move it to trash.

Again, very sorry for the troubles, this is pretty embarrassing… On the positive note, we've been very busy for the past few months and a big update with new features and app improvements is just a few days away.

**Comment by iby** [comment]
And a subsequent update was just also published to address the broken permission dialog.

![image](https://user-images.githubusercontent.com/1086845/153968889-77b6d6a7-03ff-4059-b238-bb1694916acf.png)
