### ISSUE TITLE
Forced upgrade when using Pro subscription

### ISSUE THREAD

**Issue by tir38** [Gifox/Tracker#224]
I have a paid Pro subscription. When a new version of the app is available I am forced to update to keep using Pro features. If I don't update the app, then I am locked out of Pro features. It's a minor annoyance but I'm not always ready to update.

**Comment by iby** [comment]
Hey @tir38, apologies for the lagged reply. You probably already know, this has been resolved in the update released a couple of days ago, details are [here](https://github.com/Gifox/Tracker/issues/221#issuecomment-1039212525). Let me know if there's anything else we can do?
