### ISSUE TITLE
Brew install fails

### ISSUE THREAD

**Issue by dcryan** [Gifox/Tracker#227]
First things first. Thank you for your software. I really enjoy using Gifox and always get curious questions on what tool I use for GIFs. I always send them your way.

## What's happening?

I try to install software through `brew install --cask`. Today when I tried to update, I got a 403 error.

Here's the exact error I got:

```
❯ brew install gifox --cask
==> Downloading https://d3si16icyi9iar.cloudfront.net/gifox/020300.01.dmg
curl: (22) The requested URL returned error: 403

Error: Download failed on Cask 'gifox' with message: Download failed: https://d3si16icyi9iar.cloudfront.net/gifox/020300.01.dmg
```

## What is expected?

No 403 error, and an upgrade/install of Gifox.

**Comment by iby** [comment]
Thanks for the compliments and support! ☺️❤️

We don't (for some reason 🤔) maintain the cask and it's the matter of updating it to the latest 2.3.1 version. I've never done it before and won't have time this weekend to properly fix it. Version 2.3.0 was removed because [it stopped properly working ](https://github.com/Gifox/Tracker/issues/221#issuecomment-1039212525), hence the issue with the brew install.

Please install it directly from the website and I'll try to get some time next week to update the brew cask script.

**Comment by martin-braun** [comment]
This issue is still open? It was fixed long time ago, but it broke again: 

```
==> Purging files for version 2.5.0,020500.00 of Cask gifox
Error: gifox: SHA256 mismatch
Expected: 2321f5bfe47a3b0f10abab379745b2078e65f4b997497f9789fac2c8f15cf348
  Actual: ff7bc7539e26a7115111e0c7375b6b072a12bd2e352cd1e7c662d7491ef7996a
    File: /Users/marty/Library/Caches/Homebrew/downloads/bdef275387a9327c52c7444861406ec263dcb2497283236f5b7d594eee6d00ac--Gifox.dmg
To retry an incomplete download, remove the file above.
```

It's blocking my update pipe-line, wow.

**Comment by iby** [comment]
Yep, that sucks, sorry, but we're not maintaining the Homebrew cask. I looked awhile back into that code but didn't have time to take care of it as it required some tweaks. 

From what I can tell it needs the hash to be updated – we've re-released 2.5.0, so it makes sense why it differs now. I'm not going to do make any commits there without properly looking into and understanding how to work with Casks. 

I left this issue open in hopes we can take maintenance of that code eventually, but were focused on other work. I'll keep this open, hopefully we can do this soonish. Again, sorry, I know this isn't great… 🙏

**Comment by martin-braun** [comment]
@iby Thanks, it has been fixed by a Homebrew maintainer. This issue can be closed.

**Comment by dcryan** [comment]
Confirmed. Was able to install via Brew 👍
