### ISSUE TITLE
[REQUEST] Big Sur Icon

### ISSUE THREAD

**Issue by mrleblanc101** [Gifox/Tracker#234]
macOS Big Sur launched almost 2 years ago.
Would it be possible to update the icon to adopt the new guideline ?

**Comment by iby** [comment]
Hey Sébastien! This is on the internal to-do, but I'm not that excited about simply sticking it on the white foreground… 😅 

We have a design review coming up and will definitely be having a think over that then. I'll be honest, the icon is the most I love about the current design overall and would be very reluctant to changing it unless there's a qualifiably better idea.

We love Apple guidelines and follow them as much as possible, but there are plenty of awesome ideas "outside the white box" and I'd hate to compromise between what's great and general recommendations. Just as an example, [Setapp has under it's roof some of the best apps out there](https://setapp.com/apps) – not all of them one… and some I'd remove from that list… 😅 Many of them use own designs and look absolutely smashing! Personally, I'd hated it if every single thing was strictly followed the guidelines in my Dock.

I'm going to close this down, but you've been heard and we'll have a good think about this sooner or later. No promises!

P.S. Thanks for this and other feedback and reports – it's great to speak with users and see things through different lenses! 🙏

**Comment by mrleblanc101** [comment]
Another year has passed, one of the few remaining app that I have that have an incorrect icon.

**Comment by mrleblanc101** [comment]
@iby Can we reopen this at least ? It's been another year :(
