### ISSUE TITLE
Unable to resize gifs

### ISSUE THREAD

**Issue by bensullivan-ag** [Gifox/Tracker#238]
Hi

I've tried resizing gif screen recordings to make them smaller without success - neither Scale nor Fit options seem to work.  GIFs are original sizes after export.  I'm running version 2.3.1 on a Macbook Pro M1, macos 12.3.1

Am I missing something?

Thanks

Ben

**Comment by iby** [comment]
Oh this is really embarrassing, I was piled under work and missed this, very sorry. Would love to help if you still haven't figured it out (or if there's an issue). One thing that comes to mind is I think we only support downscaling, so if you tried to upscale an exported GIF, Gifox wouldn't do that. Is that what's happening by any chance?
