### ISSUE TITLE
Copy recording to clipboard

### ISSUE THREAD

**Issue by ianbytchek** [gifox/tracker#24]
Automatically / manually.

**Comment by dimitrieh** [comment]
seriously want this ;)

**Comment by kevinsimper** [comment]
This would be the killer feature for Github project managers! and fancy developers ;)

**Comment by acheshkov** [comment]
+

**Comment by ianbytchek** [comment]
Implemented in the upcoming release! 🍾🎉 However, please be aware, gif is a special kind of animal and **pasting will not always work** as expected, like copy-pasting into GitHub or Slack, or probably any other web application. 

The reason is the way how copy-pasting mechanism on macOS works – more specifically how specific apps implement pasting. You can see that neither GitHub, Slack or YouTrack paste gifs correctly – pasted animated gif will be uploaded as static png when copied from Finder, but work correctly when dragged and dropped. One exception that we're aware of is… 🥁… 🥁… Skype!

To mitigate this we've also added drag and drop support, so you don't have to open finder every time for manual sharing. If you happen to know a solution or have an idea how we can improve this shitty experience, please let us know. Closed until then. Here's an [interesting read](https://github.com/Hammerspoon/hammerspoon/issues/737#issuecomment-173752516) on the matter from cool guys at Hammerspoon.

**Comment by dimitrieh** [comment]
@ianbytchek where can i find this feature in the recent release ? 😄

**Comment by a-vasyukov** [comment]
@dimitrieh in gif list

**Comment by thesergie** [comment]
Is there an option for it to automatically copy the image to the clipboard? Right now I have to manually click on that icon vs just going to the app (slack, github, etc) and pasting.

**Comment by ianbytchek** [comment]
@thesergie emailed you! 😉

**Comment by pbiggar** [comment]
How can you do the automatic copy that @thesergie asked for?

**Comment by ianbytchek** [comment]
@pbiggar This feature isn't implemented and not currently planned for two reasons:

1. Copy and paste is a two way road, there's no guarantee the app pasting the GIF can handle it as expected, see my [above comment](https://github.com/Gifox/Tracker/issues/24#issuecomment-314402304).
2. Less critical one, compression sometimes takes awhile, so you might end up with the GIF getting copied to the clipboard 3 minutes after recording stops – it's not clear hot to handle such situations.

For the time being we've put all integration related features on ice. At some stage we realized that this part of the app has grow out of control and takes too much effort to support as they are now. We're planning to rework sharing services into a [plugin system](https://github.com/Gifox/Tracker/issues/94), so it would be easier to maintain and use, this subject was touched in [the version 2 release highlights](https://medium.com/gifox/gifox-2-is-here-release-highlights-bc93e670388d).

**Comment by matkoch** [comment]
@ianbytchek just discovered this gem of a tool :)

A suggestion on the topic: could you trigger a native macos notification when the GIF is ready and have a _Copy_ confirm button in it? Or even two, one _Copy Path_ and one _Copy Data_ ...
