### ISSUE TITLE
cannot upgrade from gifox 1 pro to 2

### ISSUE THREAD

**Issue by Boreas-y** [Gifox/Tracker#244]
![image](https://user-images.githubusercontent.com/7846838/182516505-2633fc5d-e442-478b-a058-989fdc6c8ad3.png)
![image](https://user-images.githubusercontent.com/7846838/182516601-271662ec-bc38-4a38-b9f9-47777027605e.png)
![image](https://user-images.githubusercontent.com/7846838/182516690-5e87231c-d755-4ed3-b10d-753b6fdb19e7.png)

1.  both of 1&2 download in  app store, 1 pro is paid in app store
2. restarted computer / app store/ gifox app several times, but not work

**Comment by iby** [comment]
Hey @Boreas-y, Ian is here. I'm doing some old-issue housekeeping and forgot to respond here. Have you managed to sort this out? If not, please let me know? 🙏
