### ISSUE TITLE
error in enabling of accessibility giffox

### ISSUE THREAD

**Issue by harshavardhank4123** [Gifox/Tracker#248]
Unable to see giffox app in accesibilty section. worst experience.

<img width="503" alt="Screenshot 2022-09-13 at 1 44 39 AM" src="https://user-images.githubusercontent.com/109665478/189750156-027b8e61-1eaf-4a3e-b92f-ddfa98c1d867.png">
<img width="667" alt="Screenshot 2022-09-13 at 1 45 07 AM" src="https://user-images.githubusercontent.com/109665478/189750244-0971ba88-c78b-46a1-a4ce-6b0f0223068e.png">

**Comment by iby** [comment]
> worst experience.
Tells a lot about how much one is experienced… 😅 Love this!

Jokes aside, [this](https://github.com/Gifox/Tracker/issues/131) is a thread dedicated to the issue and this is the [answer](https://github.com/Gifox/Tracker/issues/131#issuecomment-585605922).

**Comment by harshavardhank4123** [comment]
Thank you. I forgot to add the application and I am new to mac yet to learn lot of things.

**Comment by iby** [comment]
No worries! If you have any questions feel free to ask! 👍
