### ISSUE TITLE
Rotated Output

### ISSUE THREAD

**Issue by Bohdacious** [Gifox/Tracker#250]
iPhone 13 is outputting from a slow-motion video with vertical orientation to a gif rotated right 90 degrees at bottom of gif vertical gif frame.  Top half is just grey.

**Comment by Bohdacious** [comment]
This is the output.
![2022-09-21 12 18 13](https://user-images.githubusercontent.com/114095844/191557785-af966682-72d7-4542-9a93-45163f3e0220.gif)

This is a screen grab of video.  (was too big)
![image](https://user-images.githubusercontent.com/114095844/191558169-d713cf3c-41bb-4d30-9748-569a4cfda020.jpeg)

**Comment by iby** [comment]
This has been fixed in the recent 2.6.2 release, please give it a go! It's still in review in Mac App Store, will be available for update in a day or two. Again, thanks for reporting this! ✌️
