### ISSUE TITLE
Gifox hanging on mac m1 monterey 

### ISSUE THREAD

**Issue by puma10** [Gifox/Tracker#252]
Every action leaves it to hang for a long time. 

https://www.loom.com/share/6f4ffba9a64744b1ba2c48a18e35ba9d

Happens kind of at random.  I restart and sometimes that fixes it, sometimes it doesn't.

**Comment by iby** [comment]
Hey @puma10, Ian is here. I'm doing some issue housekeeping and have completely ignored this one, apologies for the very lagged reply… 🙈

We fixed a bug a few releases ago, which could be responsible for this. Could you let me know if this was happening recently, and if so, can you please send through diagnostics data by using Contact Support inside the app? This might shed some light into what's going on.

![diagnostic-data-smaller](https://user-images.githubusercontent.com/1086845/222543604-1b564e49-3b8f-44d1-8eef-7dffb58b19ad.gif)

**Comment by replygirl** [comment]
@iby hey here's mine, same issue:

[Diagnostic Data.zip](https://github.com/Gifox/Tracker/files/11102530/Diagnostic.Data.zip)

i see in-app purchase errors (i bought pro with IAP in march 2022)

**Comment by iby** [comment]
Hey @replygirl! Thanks for sending this through and apologies for a laggy reply. We just released 2.6.1 that addresses a few issues and included several improvements. Can you please give it a go and let know if any of the issues remain?

There's nothing obvious in the logs that can point at the problem. The in-app purchase errors happened awhile ago and mean that Gifox cannot get the price details for the licensing dialog – it's normally resolved by restarting a Mac and these errors aren't present in later sessions.
