### ISSUE TITLE
Cursor position not accurate

### ISSUE THREAD

**Issue by toptaljj** [Gifox/Tracker#253]
Is there a way to manually adjust where the cursor shows up?  The interaction, "the red dot" showing click, is accurate, but as you can see here, the cursor itself is in the wrong position.  

The inaccuracy appears to be related to the cursor size accessibility option.  I like the large cursor especially in gifs that i make so that the cursor is easily seen; of course, it is a bit awkward that where the cursor points does not align properly when enlarged for greater visibility.

Thank you for gifox ❤️ very much

![2022-10-19 13 04 11](https://user-images.githubusercontent.com/1420733/196699189-0363184a-4123-4a66-a5f7-420be55c2e9a.gif)

**Comment by alexis-gervacio** [comment]
+1   I also use a large cursor and experience this issue, would love some sort of cursor offset feature if not a position fix!

**Comment by iby** [comment]
Hello friends. Thanks for reporting this and sorry for the lagged reply. This has been fixed in the recent 2.6.2 release. Please upgrade and give it another go! 👍

**Comment by toptaljj** [comment]
> Hello friends. Thanks for reporting this and sorry for the lagged reply. This has been fixed in the recent 2.6.2 release. Please upgrade and give it another go! 👍

I tested it and found it to work perfectly:

![2023-11-12 13 08 59](https://github.com/Gifox/Tracker/assets/1420733/8ed29f69-6c8e-46d8-a6f6-a32106ec69cb)

Very much appreciated!
jj
