### ISSUE TITLE
Long pause at end of loop, only after exporting

### ISSUE THREAD

**Issue by elgrayso** [Gifox/Tracker#254]
![2022-10-27 14 13 54](https://user-images.githubusercontent.com/65375493/198389473-a210d9e8-942f-44cd-8e89-a214be14eb38.gif)

Every looped file I create has a long delay/pause at the end, rather than a seamless loop. It looks fine in Gifox but goes wrong when exported.

**Comment by elgrayso** [comment]
System: MacBookPro18,2 Version 12.2.1 (Build 21D62)
Memory: 224.9 MB (64.0 GB)
Processor: Apple M1 Max: 10.2% (16.2%)
GPU: Apple M1 Max
Display: <"BenQ EW3270U (1)" main: true, scale: 1.0, frame: (0.0, 0.0, 3840.0, 2160.0), bounds: (0.0, 0.0, 3840.0, 2160.0), color space: "BenQ EW3270U colorspace", refresh rate: "60.0 Hz">, <"BenQ EW3270U (2)" main: false, scale: 1.0, frame: (3840.0, -903.0, 2160.0, 3840.0), bounds: (0.0, 0.0, 2160.0, 3840.0), color space: "BenQ EW3270U colorspace", refresh rate: "60.0 Hz">
Power: <"InternalBattery-0" capacity: 80%, charging: false, charged: false>

**Comment by iby** [comment]
Hey @elgrayso, Ian is here. I'm doing some old issue housekeeping and looks like this one slipped through my fingers – sorry.

Yes, the delay at the end of a GIF is a GIF-format feature and it's added when a GIF is exported. You can adjust this per existing recording in editor in [export configuration](https://gifox.app/docs/exporting#export-configuration), or globally for new recordings / imports in [Export Preferences](https://gifox.app/docs/using-gifox#preferences-window).

I'm going to close this down, but please feel free to comment if you want to discuss this further! 👍
