### ISSUE TITLE
Restore Purchase

### ISSUE THREAD

**Issue by audemxrs** [Gifox/Tracker#257]
Hello,

I purchased this app in 2017, to remove the water mark (pro version) Now there is an update, may I know how to reactivate my purchase / restore my purchase?

![download](https://user-images.githubusercontent.com/83077950/221837516-13801d78-708f-4aa1-afe1-4f9591f7bd2b.png)

**Comment by iby** [comment]
Hey @audemxrs, Ian is here! We replied to you via email yesterday. We try to keep all purchase and any personal-details-related conversation to email channel. If you need any further help with that please respond to the email and we'll be in touch! 🙏
