### ISSUE TITLE
v.2.6 keyboard interaction capture does not display text/numbers

### ISSUE THREAD

**Issue by ehabibov** [Gifox/Tracker#259]
Notice neither text, nor numbers displayed, but cmd modifier key is.
macOS Monterrey 12.6.5 (21G531)
Gifox 2.6.0 (00)
U.S. locale

![2023-04-28 14 51 59](https://user-images.githubusercontent.com/20490584/235140782-bfdea830-eced-4ef1-9677-98e8161d6de3.gif)

**Comment by iby** [comment]
Hey @ehabibov, thanks for reporting this and apologies for the laggy reply. This is pretty interesting… I'm guessing this is an Android simulator? Can you confirm exactly the app name and version? Neither of us have it installed, so we can't test it. But I just tested the latest Gifox 2.6.1 version with iOS simulator and everything seems to be acting as expected.

The reason why this might be happening is Android simulator using some private API to catch keyboard events and prevent them from further propagating, meaning no other apps will receive it. I've never seen this behaviour before, but if this is the case, then I'm not sure if we can do much about it. But I'd definitely would like to test it.

Another idea that comes to mind is if you're using the Mac App Store and not direct-download version. Direct-download version doesn't use sandboxing – in theory that shouldn't matter, but with lower-level APIs it might be acting out. If you're not using the direct-download version, could you give it a go and see if it works any different with that app?

![2023-05-08 20 29 05](https://user-images.githubusercontent.com/1086845/236915648-eb8e10f5-4243-459c-a820-09f281241528.gif)

**Comment by iby** [comment]
@ehabibov I'm gonna close this issue. If you're still having issues, please send through diagnostics data and we'll have another look! 👍

![diagnostic-data-smaller](https://github.com/Gifox/Tracker/assets/1086845/25d4c11e-ad97-4abe-9943-9109b54a5aef)
