### ISSUE TITLE
Unable to connect Dropbox - receiving "circular loop" style error telling me to update my browser

### ISSUE THREAD

**Issue by Eqxlt** [gifox/tracker#262]
I am trying to connect my Dropbox account to my Gifox Pro 2.6.1 software. I keep getting a message regarding my browser not being up to date. Safari is my default browser and it is up to date.

I am using a MacBook Pro M1 13.4.1 (22F82). 

I have attached screenshots of the message that I received. 

![Screen Recording 2023-07-13 at 12 37 15 AM](https://github.com/Gifox/Tracker/assets/40595814/6153079f-b974-45b3-86e2-3fe8e0ef0dc8)
![Screen Recording 2023-07-13-2 at 12 37 15 AM](https://github.com/Gifox/Tracker/assets/40595814/16161d0b-e5b1-4a1b-845c-a64248075f5c)

I have been able to connect Drive, but I would prefer DropBox as I have more space.

Thank you.

**Comment by taramk** [comment]
i'm getting the same error. this is blocking me from using dropbox.

**Comment by iby** [comment]
Hey @Rbxt and @taramk, sorry for the lagged reply and thanks for reporting this. The fix is coming up in the next release in a couple of days. 🙏

**Comment by iby** [comment]
This has been fixed in the recent 2.6.2 release, please give it a go! It's still in review in Mac App Store, will be available for update in a day or two. Again, thanks for reporting this! ✌️
