### ISSUE TITLE
Gifox with macOS Sonoma Version 14.0 (23A344)

### ISSUE THREAD

**Issue by GheorgheSacultanu** [gifox/tracker#268]
Dear DEV Team,

Recently I did a macOS upgrade to Sonoma and activated the license for Gifox and I have started to see some issues with it.

1) For the Capture settings I have the option: Cursor, Mouse interaction, and Keyboard interaction but as you can see it's not showing the red point where I make the click
![2023-10-25 17 19 55](https://github.com/Gifox/Tracker/assets/19188589/25115e00-9889-4555-9721-562b2128c5bd)
2) The length of the video is every time less by few seconds compared with when I press Stop recording. (for example, if I record 30 seconds then the gif will show that I have recorded only ~ 24 seconds.

The registered email for the license is : sacultanugheorghe@gmail.com
Gifox version: 2.6.1
![2023-10-25 17 24 02](https://github.com/Gifox/Tracker/assets/19188589/e4a80e0b-879f-4de9-becc-9a1e0674f2fd)

Thanks in advance for your investigation.

Regards,
Gheorghe SACULTANU

**Comment by iby** [comment]
Hey @GheorgheSacultanu, thanks for reporting this. We're looking into this issue, both with the cursor and cutting off videos. There's a [separate issue](https://github.com/Gifox/Tracker/issues/267) for the videos getting cut off, if you are able to provide additional info in that thread – would be very helpful, thank you! 🙏

**Comment by GheorgheSacultanu** [comment]
Added all the required details on that mentioned issue.

**Comment by kmayhew-cf** [comment]
@iby I have just noticed today that I am also experiencing the issue with the mouse clicks not being identified in the GIF.

**Comment by iby** [comment]
@GheorgheSacultanu @kmayhew-cf I'm going to close this down. The issue with interactions is another problem on Sonoma we and other developers are facing. We're tracking it in #266, I'll post updates there. Will also aim to provide a fix in the upcoming Beta next week.
