### ISSUE TITLE
Is it possible to make the background transparent when enabling window shadow?

### ISSUE THREAD

**Issue by pacmandoh** [gifox/tracker#269]
As mentioned in the title

**Comment by lerinagalimova** [comment]
Hey @pacmandoh! We discussed this in details in #207 , please have a look there. Now that we support importing other formats, supporting opacity can be useful – we have this in our internal backlog. However, with GIF limitations in mind, this won't work as expected for shadows, gradients or any alpha transparency.

**Comment by pacmandoh** [comment]
Thanks a lot! ❤️ ,  I understand what you are saying
