### ISSUE TITLE
Record and display mouse and keyboard activity

### ISSUE THREAD

**Issue by JKillian** [gifox/tracker#27]
Showing keystrokes pressed during a recording would be a great option to have! Would help me when I'm capturing a gif of a software bug or demonstrating usage of something.

**Comment by ianbytchek** [comment]
@JKillian thanks for bringing this up – there's no public issue for that, but this is something indeed very useful and definitely planned. Should also include mouse activity.

**Comment by Modi34** [comment]
in case you will add it please consider user lang input - I use https://www.boinx.com/mousepose/overview/ for this and when I type something on my native lang (Russian) it is in english and it is very frustrating 

https://drive.google.com/file/d/0B3twjDbcZ99uRjUteGdLaWhVY0E/view?usp=drivesdk

also screen annotation will be great - if you want I can show an example of it//

**Comment by ursbraem** [comment]
Only things I'm missing from http://silverbackapp.com/ (which I used to abuse for documentation purposes): Showing keystrokes as well as Cursor clicks

**Comment by dsuriano** [comment]
**+1** for the ability to toggle visible mouse clicks during recording. This is essential for conveying non-responsiveness of elements within a UI during the testing phase.

**Comment by Nigelw** [comment]
+1 for showing mouse clicks & key presses.

On the topic of mouse activity, it would also be extra nice to have an option to show scroll actions. This isn't nearly as important as showing mouse clicks, but sometimes I need to capture issues relating to scrolling. E.g. sometimes I need to demonstrate that scrolling doesn't work or exhibits bugs, and having a visible scroll indicator would help show what's triggering these actions on screen.

**Comment by adeanzan** [comment]
Being able to display keystrokes is the only thing preventing me from paying for gifox. It would really set it apart from all the other gif recorders.

**Comment by ursbraem** [comment]
Nice, thanks, also see: https://github.com/keycastr/keycastr/issues/46 (the key display can be dragged)

**Comment by ursbraem** [comment]
In regards to click highlighting: nothing speaks against doing that outside of gifox as well! I found a few old-ish apps on the MAS; but maybe someone has a recommendation for that as well?

**Comment by seanparmelee** [comment]
[GIPHY Capture](https://giphy.com/apps/giphycapture) shows clicks, but I would love to have this feature in Gifox.

**Comment by cryogenx** [comment]
cant wait for this!

**Comment by microbit-carlos** [comment]
First of all, great work on gifox.
From my perspective this really is the last missing feature for this app to become the best GIF recorder on macOS. It will be immensely welcomed whenever you have a chance to include, thanks @ianbytchek!

**Comment by carlosperate** [comment]
First of all, great work on gifox.
From my perspective this really is the last missing feature for this app to become the best GIF recorder on macOS. It will be immensely welcomed whenever you have a chance to include, thanks @ianbytchek!

**Comment by NathanBowers** [comment]
+1 for an option to show clicks in the recording.

**Comment by juliandesmarais** [comment]
LICECAP is a free app and has this feature. Considering I paid for Gifox would be nice to have it as well

**Comment by ianbytchek** [comment]
Mouse activity recording is available in [Gifox 2 Beta](https://gifox.io/prerelease). Keyboard activity capturing will follow a little later. Stay tuned.

**Comment by cryogenx** [comment]
Can confirm its working great. Cant wait to see the keyboard stuff.. Keycastr is great but I would love something that knows where to position itself based on my selection.

**Comment by JKillian** [comment]
Excited to try out this feature! Is there a way to try out the beta if we have a pro license bought through the mac store @ianbytchek?

**Comment by ianbytchek** [comment]
Not for Mac App Store users I'm afraid. Some also report a problem in the lates macOS update with black video editor output. A new update is coming up shortly, stay tuned! 👍

**Comment by ianbytchek** [comment]
152 years later and this feature finally made it into Gifox 2 Beta… 🤦‍♂️😓 Version 2.0.0-beta.3 to be precise and will be released in a few days. Thanks for all of your patience and support fellas! ✌️

![2019-06-06 18 41 59](https://user-images.githubusercontent.com/1086845/59043333-18d6b000-888d-11e9-979e-f19a6fefd456.gif)

**Comment by Thegrtn** [comment]
@ianbytchek, I just wanted to add here as well. I have really enjoyed using this application, and can't wait for these additional features!

Is there a set release date for V2.0.0 for the Mac App Store?

**Comment by ianbytchek** [comment]
@Thegrtn, I responded to your email last night, but the mail server responded with "Address not found". Anyway, seems like you found the beta without it! Regarding the App Store release, I wouldn't promise anything, but hopefully in two-three weeks – there're a couple more important improvements on the to-do. But it might take longer than planned, as usual… 🤷‍♂️

**Comment by Thegrtn** [comment]
> @Thegrtn, I responded to your email last night, but the mail server responded with "Address not found". 

Hmmm, that's weird. I guess my work domain might have blocked the response, or I could have just mistyped the email address itself.

> Regarding the App Store release, I wouldn't promise anything, but hopefully in two-three weeks – there're a couple more important improvements on the to-do. But it might take longer than planned, as usual… 🤷‍♂️

Thank you for your timely reply. I totally understand. Thanks again for actively improving this already great application! 🙇‍♂️ I'll eagerly await the App Store release in the meantime!

**Comment by Nigelw** [comment]
I just tested Gifox 2 beta 3. For some reason keyboard activity isn't being captured, despite making sure the checkbox is checked. Anything I can do to help debug?

(FWIW capturing mouse activity works great. And I'm v excited for all the new functionality. v2 release is a huge update.)

**Comment by ianbytchek** [comment]
@Nigelw Hmmm… The build 4 is underway. Would be of huge help if you can check and confirm there. In the meanwhile, please send an in-app feedback to include logs – they might shed the light into what's going on. Keyboard capture relies on GPU and hardware acceleration, so might not work if that's not available. But again, logs should provide clues. Thank you!

**Comment by Nigelw** [comment]
@ianbytchek sorry for the delay. I just sent in-app feedback so that you have logs. I'd be happy to check build 4 as well – just let me know where I can download it.
