### ISSUE TITLE
Gifox menu often inaccessible in fullscreen mode on 14" MacBook Pro

### ISSUE THREAD

**Issue by kevinebaugh** [gifox/tracker#270]
On a 14" MacBook Pro, when in fullscreen mode for any app, it's hard to get to the Gifox menu. Here's a Loom explaining:
><a target="_blank" href="https://www.loom.com/share/f83b8fe8cf7e4bf29dbd329f6a272e23"><img src="https://cdn.loom.com/sessions/thumbnails/f83b8fe8cf7e4bf29dbd329f6a272e23-with-play.gif"/></a>
>[0:04](https://www.loom.com/share/f83b8fe8cf7e4bf29dbd329f6a272e23?highlightComment=26849558&t=4): No problem reaching the menu when not in fullscreen.
>[0:09](https://www.loom.com/share/f83b8fe8cf7e4bf29dbd329f6a272e23?highlightComment=26849606&t=9): When in fullscreen mode, the menu often hides before I'm able to get to it.

System info:

<img src="https://github.com/Gifox/Tracker/assets/3092522/c1d64ee8-fc2c-4489-b1d6-984b593e6f49" width="50%"/>

**Comment by iby** [comment]
Hey @kevinebaugh, thanks for the detailed report! I'm a little tight on time this week, will review and get back on this in the next couple of days! 👍🙏

**Comment by kevinebaugh** [comment]
This appears to be fixed in Sonoma 14.5 (23F79) 🎉
