### ISSUE TITLE
always keeps believing there is a conflict with the output directory

### ISSUE THREAD

**Issue by mpstaton** [gifox/tracker#273]
Every time I open Gifox, the directory that I used last time I used Gifox throws an error.  It asks me to assign it to another directory.  So now I have two GIF directories.  

Not the biggest time waster, but it's pretty annoying.

**Comment by iby** [comment]
Hey @mpstaton, thanks for reporting this! Hmmm, sounds odd, can you please send the diagnostic data with logs so we can get additional details and hopefully figure out w hat's wrong? 🙏 Feel free to email it directly, if don't want to post it here.

![diagnostic-data-smaller](https://github.com/Gifox/Tracker/assets/1086845/bace4c2a-3566-4d15-99a3-9e25c5a43803)

**Comment by iby** [comment]
I believe this is the same issue as #275 – seems to be happening in Mac App Store release. Will try to fix in the upcoming release! 👍

**Comment by iby** [comment]
@mpstaton we just released an update addressing this and a bunch of other issues with editor. Please get the latest version and let me know if you run into anything else? Thanks for reporting this and all the feedback! 🙏
