### ISSUE TITLE
Bug: Cut + change speed causes glitches

### ISSUE THREAD

**Issue by angel-luis** [gifox/tracker#276]
**M2 - 14.2.1**

I've been doing a lot of gifs so far and the most of the time when I use the cut tool and also I change the speed in the same editor session, it creates artifacts. I think is failing because first tries to change the speed before cut the clip, because the glitch is always at the end of the gif.

An example:
- In any clip, you make a cut
- You speed up 2x
- You have the clip of X seconds, but some of the seconds at the end, are glitched by a fixed background

Isn't shown in the timeline, but when you copy the clip, it appears the glitch.

**Comment by iby** [comment]
Hey @angel-luis, thanks for reporting this! This is related to #265. We're working on a fix, hoping to publish a new release with the fix this week.

**Comment by angel-luis** [comment]
Yeah I've been checking and also the crop tool isn't working (when combined with other tools), at least the cut tool it is. :)

**Comment by iby** [comment]
@angel-luis sorry for going off the radar – I discovered a bunch of other related issues while working on a fix and got "slightly" carried away. We just released an update earlier today that addresses this and a bunch of other problems with speed-adjusted recordings and editor in general. Please update to latest and give it a try. Again, thanks for reporting this and let me know if you run into anything else! 🙏
