### ISSUE TITLE
Xcode Sim Gifs

### ISSUE THREAD

**Issue by logancautrell** [gifox/tracker#278]
They don't work after import. I just installed this app. Using Mac 14.4.1 (23E224)

It is frustrating.

**Comment by logancautrell** [comment]
I resized the timeline and it finally worked? There is definitely some improvements for simulator that needs to be made. I shouldn't have to jump through all these hoops. The app does not remember my previous screen positions.

**Comment by iby** [comment]
Hey @logancautrell! 👋 Thanks for the feedback. While I understand you've spent the time time writing it out of the best intentions and in hopes things can be improved, and we value everyone's input for these very same reasons… it's equally frustrating reading yours:

> They don't work after import. I just installed this app.

Who doesn't work after what import and where? GIFs out of Gifox? On a particular websites? In a particular app? Or Xcode Sim Gifs imported into Gifox?

> I resized the timeline and it finally worked?

Is that a question or a statement?

> There is definitely some improvements for simulator that needs to be made.

100%, but I hope we agree that Xcode simulator improvement suggestions are best to be addressed to Apple, not us?

> I shouldn't have to jump through all these hoops.

Please don't.

> The app does not remember my previous screen positions.

Yes, it doesn't… until you press a lock button in selection menu.

I'd be happy to help, but please take a moment formulate what's wrong or not working as you expect – as a developer yourself, I'm sure you're familiar with what constructive and helpful feedback looks like! 👍
