### ISSUE TITLE
Is there a way to save the previous selection so every time I toggle area selection, it sets that by default?

### ISSUE THREAD

**Issue by RobbieZhuang** [gifox/tracker#283]
Hi, I'm using the free version of Gifox. Often I have to rerecord because I make a mistake in my previous recording and re-selecting the same spot is a pain. 

Does this functionality (saving and automatically loading the previous selection) exist?

**Comment by lerinagalimova** [comment]
Hey @RobbieZhuang , what you are looking for can be achieved by pressing the lock button in the top right corner of the selection menu – it's not very obvious, but it does exactly what you're after. We have an upcoming UI review, will hopefully make this clearer. Let us know if we can help with anything else or if you have any feedback? 👍
<img width="223" alt="PastedGraphic-1" src="https://github.com/user-attachments/assets/449b6b27-0863-473b-ba67-01cb722c244d">

**Comment by RobbieZhuang** [comment]
Ah, I totally missed that, thanks!
