### ISSUE TITLE
License not available anywhere

### ISSUE THREAD

**Issue by cstrab** [gifox/tracker#288]
I purchased Gifox from the app store and never received a license ID. After restarting my Mac one day it now says I don't have a subscription. I have sent an email to Gifox support and have not received anything... I have also tried to login to this Paddle.net which does not show my license either.

So now I am stuck not able to use pro somehow...

**Comment by lerinagalimova** [comment]
Hey @cstrab, thank you for following up! It turns out your email accidentally went to our spam folder, and it got a bit lost. I’ve responded to your question via email now, so please check your inbox.

Apologies for the delay, and thank you for your patience!✌️
