### ISSUE TITLE
Consider adding better control over mouse cursor in recording

### ISSUE THREAD

**Issue by ianbytchek** [gifox/tracker#3]
1. Hide mouse all together from the recording.
2. Use ripple effect to indicate mouse got clicked.

**Comment by maxhoffmann** [comment]
These options would make the app perfect! 💯

**Comment by cryogenx** [comment]
isn't this basically the same as [#27](https://github.com/gifox/tracker/issues/27l)

**Comment by ianbytchek** [comment]
@cryogenx good point. Cursor can be already hidden in preferences. The rest is #27 indeed. Thanks!
