### ISSUE TITLE
Huge cursors on Siarra with retina

### ISSUE THREAD

**Issue by ianbytchek** [gifox/tracker#30]

**Comment by dimitrieh** [comment]
probably an instance of this bug mentioned here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/6494

**Comment by ianbytchek** [comment]
There was an opposite problem in pre-10.12, now the fix turned into a bug. Will release a patch in a couple of days, sorry all.

**Comment by ianbytchek** [comment]
Apple reviewing the build, will come available shortly.
