### ISSUE TITLE
Integration notifications should open share urls in browser

### ISSUE THREAD

**Issue by Modi34** [gifox/tracker#32]
I use mac2imgur for ordinary screenshot capturing - https://www.dropbox.com/s/mfi7ew8k16pze3m/2016-09-24%2013.11.21.gif?dl=0
this is an example how notifications are implemented there

description has a link to screen and If I click on notification image is being opened
It would be really nice if on gifox notification click popup would appear with image selection

**Comment by ianbytchek** [comment]
That's really cool. We definitely need this. Notifications are there, but a little useless as they are now – this would close the gap.
