### ISSUE TITLE
Supporting other image / video capture formats

### ISSUE THREAD

**Issue by Modi34** [Gifox/Tracker#34]
Gifs are great but if there will be an ability to capture just screens everything will be in one app and in one pop up - that will really improve my workflow)

**Comment by ianbytchek** [comment]
This is an intriguing idea, we had a few requests before, but it feels like a deviation from the current course. I'll keep this as a reminder, will come back to this later.

**Comment by ianbytchek** [comment]
Okay, we finally have a solution for this without bloating the app. Still not sure about screenshots. This is tracked in #130.
