### ISSUE TITLE
Crashes as soon as I try to record by selecting an area

### ISSUE THREAD

**Issue by jbucaran** [gifox/tracker#40]
Hi! I just purchased Gifox to record a problem I had with another app and report the issue, but ended up opening an issue here first.

Gifox crashes as soon as I try to record by selecting an area.

**Comment by ianbytchek** [comment]
Thanks for reporting! We've seen a few rants about similar random crashing, but have no actual details on what's going on. Can you confirm if your output directory is selected preferences before recording? Try selecting a different one? Really want to get to the bottom of this, any further details would be much appreciated!

**Comment by jbucaran** [comment]
Hi. Yes, the output directory is selected. I also tried changing it to a different directory, but the behavior persisted.

Just now, before I posted this reply, I was able to record for almost 10 seconds, stopped the recording, but it crashed before the gif could be written to the selected output directory.

One more thing, not related for sure, but just in case, there's always a strange pixel off on the left upper corner of the crash report window. See below.

<img width="724" alt="screen shot 2016-12-03 at 0 51 14" src="https://cloud.githubusercontent.com/assets/56996/20840194/bf4c7338-b8f2-11e6-9f41-e68659930e28.png">

One thing I forgot to mention, I'm on Sierra.  Late 2016 MBP.

**Comment by ianbytchek** [comment]
That's great, I got your reports and have an idea about what might be going wrong. There's a long awaited update on its way, hoping to push it into the App Store early next week with the fix.

**Comment by ianbytchek** [comment]
@jbucaran do you use custom cursors by any chance or are they configured for accessibility somehow? Or is the cursor when you record is a non-standard one? From the screenshot I see that button colours are slightly darker than usual, I'm curious if that's the system-wide UI configuration or only Gifox?

**Comment by jbucaran** [comment]
> There's a long awaited update on its way, hoping to push it into the App Store early next week with the fix.

@ianbytchek Sounds great! Thanks.

> do you use custom cursors by any chance or are they configured for accessibility somehow? ...

Those things you noticed are my accessibility custom display settings. Slightly larger than usual cursor and more contrast. Here it is.


<img width="433" alt="screen shot 2016-12-03 at 15 01 32" src="https://cloud.githubusercontent.com/assets/56996/20857281/839b3c4e-b969-11e6-8df4-de27f119423c.png">

**Comment by ianbytchek** [comment]
@jbucaran it took us outrageously long for the promised release, apologies, but we've completely reworked several mechanisms related to this error. Please update to 1.2.4 when it becomes available in the App Store in a couple of days and see if it helps?

**Comment by jbucaran** [comment]
@ianbytchek Will do! Thanks a lot.

**Comment by ianbytchek** [comment]
@jbucaran it should be live.

**Comment by ianbytchek** [comment]
Jorge, from the logs I see that you're still getting this issue, which is bizarrely odd. I went through all available logs and found only a few more instances of this problem, it's very rare and I'd like to get the bottom of this. We'll try to include another fix in 1.2.5, which is expected in a few days, but we might need some extra information from you. Would it be ok for you to run a small test and post back the results?

**Comment by jbucaran** [comment]
@ianbytchek Yep. I'd love, just let me know what I need to do to help.

**Comment by ianbytchek** [comment]
We found the problem – this is happening on retina screens with upscaled I-beam and potentially a few other cursors, default upscaled pointer cursor and most other cursors work fine. This explains  why it wasn't a straight discovery and why you're getting this with terminal. Hopefully the new solution will cover in full all of these newly discovered extreme cases and we can close this in a couple of days. Fucking hell…

**Comment by jbucaran** [comment]
@ianbytchek Great news! 

P.S: So sorry to be such an extreme case, but I can't wait to get my hands on the latest patch.
