### ISSUE TITLE
Shortcuts conflict with Skitch

### ISSUE THREAD

**Issue by raisedadead** [gifox/tracker#41]
Both <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>5</kbd> and <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>6</kbd> are shortcuts from Skitch app. 

I use its all the time, and Gifox's shortcuts are conflicting. There is no way to avoid conflict unless I close Skitch, use Gifox and restart Skitch again, close Gifox.

This is potentially slowing me down in the workflow.

Please consider adding support for custom shortcut ASAP (I know it's the plan). Just reporting the conflict, with a very popular application.

Awesome app BTW! 👏

**Comment by ianbytchek** [comment]
This is coming up in the next 1.2.5 release. We wanted to squash it into 1.2.4, which just was submitted to the App Store, but didn't manage to, sadly!

This is probably the most popular request recently, I've also seen a few references to Skitch in the past. This made me curious, doesn't Skitch allow changing shortcuts? :smile:

**Comment by raisedadead** [comment]
@ianbytchek Thanks for the update.

> doesn't Skitch allow changing shortcuts?

Sadly no, I didn't find any options in their menu, preferences, etc. Looked up on Google and found that only way on newer OSX is to go the keyboard shortcuts in the System Preferences and mess around. 😞 😞

**Comment by ianbytchek** [comment]
Expect in a few days.

**Comment by raisedadead** [comment]
Awesome! Thanks.
