### ISSUE TITLE
Integration "user Rate Limit Exceeded"

### ISSUE THREAD

**Issue by kieranju** [gifox/tracker#42]
Integrating my Google Drive account works, however the app is unable to list the root folder.

> Failed to list
> Something went wrong while listing the root folder in GoogleDrive / myemail@gmail.com account with the following message: user Rate Limit Exceeded
>
> That's all we know. If this keeps happening try re-authorising associated integration of file a bug report.

Feel free to ask me for any details pertaining to this, it looks like it could be related to GDrive's API restrictions in some way. I only have a few folders in the root directory as well.

I also know it's bad practice and I should open another issue, but in the above error: 

- ~~re-authorising~~ re-authori**z**ing
- ...associated integration ~~of~~ **or** file a bug report

**Comment by ianbytchek** [comment]
Hmmm… :confused: We're seeing this more and more. It's unclear what's going on, but seems like a problem with each individual account. Gifox attempts to list 3 folder levels before showing them in the browser window, so if anywhere in these 3 levels you have a lot of folders, the api might issue this error. This is my current understanding.

So, as a workaround, we probably will limit listing to one level only for now. Then we can implement progressive listing or some other smart mechanism.

**Comment by kieranju** [comment]
That would make sense! I do have a ridiculous amount of nested folders in an attempt to keep things organized 😁

**Comment by ianbytchek** [comment]
The update is on its way guys. Hang on for a couple more days!

**Comment by marcusmoore** [comment]
Hello! Any updates on this?

Thanks!

**Comment by ianbytchek** [comment]
@marcusmoore and everyone, sorry for the delay. The new build is ready, but we're sorting out some related org matters, literally hours away from submitting it for review. It will be in the App Store by end of the week! 💯

**Comment by ianbytchek** [comment]
Hey everyone, just a quick update with bad news. Apple rejected the latest build for second time, there is a problem with frameworks signatures in 10.10 – app is working in 10.11 onwards, but goes down in flame on 10.10. As you can imagine, this took a little while figuring out wtf is going on. Now that we know the issue the solution should follow shortly. Again, sorry for delaying the release, I know it's an important one, we're working around the clock to get this up and running. 💪

**Comment by ianbytchek** [comment]
1.2.6 just landed in App Store, please update.

**Comment by JustinBeaudry** [comment]
`1.6.1` on macOS `10.14.4` has the same issue.
