### ISSUE TITLE
Don't add watermarks to gifs

### ISSUE THREAD

**Issue by JKillian** [gifox/tracker#43]
Please don't add a watermark to gifs! For small gifs, it makes the gif completely unreadable:

![2017-01-23 18 50 53](https://cloud.githubusercontent.com/assets/1400151/22195728/8302504a-e19d-11e6-82a5-773939219c3c.gif)

But even if the gif wasn't small, since giffox is paid software, adding a logo feels a little tacky. On the other hand, if you were to make a free version of giffox, adding a watermark like this would be a good differentiation between the free/paid version.

**Comment by ianbytchek** [comment]
James, thanks for reporting this and sorry you're seeing this. I'm afraid you came across a hidden treasure – this is part of the beta version functionality, which is not available yet. The only reason you might be getting this is wrong / lost / damaged app receipt, in which case you'd normally get a notification at launch. The simplest fix is to quit and relaunch the app, if it doesn't help, try trashing the app and reinstalling it from the App Store. Please let me know how it goes, very curious if this ever happens again?

**Comment by JKillian** [comment]
Thanks for the tip @ianbytchek, restarting gifox fixed it! Should've tried that first I guess 😁 

Anyways, if this is part of an upcoming free/demo version of the app (which seems like a great idea for users who like to try before they buy), it would be nice if the logo is scaled down for small gifs. Things all fixed on my end though, so thanks!

**Comment by JKillian** [comment]
Hi @ianbytchek. Your solution is still working for me - I can close and restart gifox and the watermark goes away. However, I'm seeing this watermark often, and it slows down the process of recording a gif when I have to restart gifox almost each time I use it. Do you have any advice on how to fix this? Is there something I can do on my end to fix this if it's an app receipt issue?

**Comment by ianbytchek** [comment]
@JKillian I doubt it's a problem with a receipt if you are getting it that often, must be a glitch at our end. Can you think of a pattern when it happens? Maybe when your mac wakes up from sleep? Maybe just after a prolonged period? This definitely needs fixing in a priority matter, but I'm a little clueless how to reproduce.

**Comment by JKillian** [comment]
> Maybe when your mac wakes up from sleep? Maybe just after a prolonged period?

Something like this is my guess. I'm not sure though, I'll pay specific attention to it and get back to you if I notice anything concrete

**Comment by JKillian** [comment]
Still seeing this issue, unfortunately haven't been able to determine a root cause. Will let you know if I figure anything else out though!

**Comment by ianbytchek** [comment]
Is this in 1.2.7?

**Comment by JKillian** [comment]
Yep! I'm still not sure if it's some problem with my environment signing me out of the app store and doing weird things or a gifox specific issue. But restarting gifox does seem to fix things whenever there's an issue.

**Comment by ianbytchek** [comment]
Should be resolved in the next version.
