### ISSUE TITLE
Sometimes recording halts when I CMD+V paste

### ISSUE THREAD

**Issue by JKillian** [gifox/tracker#48]
I'm sorry I don't have better info on this bug, but I've noticed that my recording often seems to stop after I press CMD+V to paste anything. The recording is saved correctly up and contains what I've recorded up until the time I pressed CMD+V.  I'm not sure if this happens with any keypress or only with pasting, and it only happens intermittently.

**Comment by ianbytchek** [comment]
😄 I love these bugs! Will look into this. Jason, as always, thanks for reporting. This is a massive help!

**Comment by JKillian** [comment]
Could this be related to the watermark bug? I.E. when in watermark mode you're also not allowed to press keys while recording? That's probably crazy, but just checking 😁

**Comment by ianbytchek** [comment]
Nope, but that makes me think… If you're seeing watermarks it means the app thinks it's unlicensed, which means the recording time should also be limited to 10 seconds, in fact you should see the counter at the top going from 10 to 0, not from 0 to ∞. Can you confirm whether this is the case to eliminate the obvious next time you see the watermarking your gifs?

**Comment by JKillian** [comment]
Ha, you know, I bet that's it. And the few times I've recorded a gif over ten seconds, I probably just happened to hit some keystrokes right around the ten second mark. I'm going to say this is a manifestation of #43 and close the issue, but I'll reopen it if it occurs again on a non-watermarked gif.
