### ISSUE TITLE
Touchbar support? 

### ISSUE THREAD

**Issue by NuroDev** [Gifox/Tracker#53]
> Adding touchbar support, even if it's just 2 buttons for selecting either area or window recording, would be super handy 😄

**Comment by ianbytchek** [comment]
We'll do this in 2.x release, backlogging for now – with so many open issues and feature requests touchbar support coming first would be an insult to many 😉

**Comment by cryogenx** [comment]
this would be AMAZING

**Comment by iby** [comment]
I'm tidying up some old issues. Looks like this is no longer happening… 😅 I hated the touch bar idea so much I ended up waiting out on upgrading my Mac between then and now… 😅

**Comment by iby** [comment]
And Gifox too… 😅🤦‍♂️
