### ISSUE TITLE
Gifox is completely unusable at the moment for me

### ISSUE THREAD

**Issue by dimitrieh** [gifox/tracker#56]
I already sent a few reports in (1 just 1 min ago) via the native reporting way of apple.

I have no idea what's happening.. as soon as I press record.. the whole application crashes.

cc: @ianbytchek

**Comment by ianbytchek** [comment]
I know, sorry about this! 😖 The last update went wrong big time. The fix is in the works coming up hopefully tomorrow or over the weekend. This is urgent!

**Comment by dimitrieh** [comment]
thanks! no problem good to know its known ;)

**Comment by ianbytchek** [comment]
We found the issue and it's extremely dumb. ☹️ With the fix on its way, right now you can simply re-select dither in compression settings or reset compression settings altogether.

![image](https://user-images.githubusercontent.com/1086845/27469486-d0ed1e8c-5800-11e7-8aa1-19e9f98be61e.png)

**Comment by dimitrieh** [comment]
thanks! seems to work!

**Comment by Wilsonilo** [comment]
Perfect, thanks for the fix!
