### ISSUE TITLE
Be able to edit your created gif's start and end (and split in between)

### ISSUE THREAD

**Issue by dimitrieh** [gifox/tracker#58]
Basically, basic video editing features for your gif (think of uploading a video to whatsapp)

**Comment by cryogenx** [comment]
would love to see this as well as the ability to resize/resample captured gif

**Comment by ianbytchek** [comment]
We've been working our asses off on this. Some really cool stuff coming later this summer. Do stay tuned! 🌶

**Comment by cryogenx** [comment]
will do, I think this app has great potential, it produces the smallest gif that I've seen from any competing apps thus far, i went ahead and purchased bc i think its got a lot of potential

**Comment by ianbytchek** [comment]
Implemented in Gifox 2 Beta. Stay tuned!
