### ISSUE TITLE
Can't capture windows

### ISSUE THREAD

**Issue by jonahwh** [gifox/tracker#59]
When trying to capture windows, Gifox only seems to be able to latch on to "Window Server", which just captures a tiny fragment of the screen.

As I move the mouse around, windows get highlighted for a split second, but it quickly switches back to "Window Server", and I cannot capture anything.

macOS 10.12.6
Gifox 1.2.10

**Comment by a-vasyukov** [comment]
Try to update Gifox to latest version 1.3.0

**Comment by ianbytchek** [comment]
@jonahwh did you solve this? There were some issues in the past, which were resolved. There are a few variables when it comes to window selection and capturing. I'd love to know if you've discovered a new case?

**Comment by jonahwh** [comment]
I think I've seen it once since updating. I think both times it occurred, it was after I disconnected two external displays and took the laptop out of clamshell mode. But it definitely doesn't happen every time.

**Comment by ianbytchek** [comment]
Hmmm, screen connecting / disconnecting might be related, I'm gonna close this, but keep your finger on the pulse and let know if this happens again. I'll also have another look into multiple screens.

**Comment by ianbytchek** [comment]
Looks like this is still hunting the latest version… #129
