### ISSUE TITLE
Allow Users to "Drop" Video Files into Gifox to Convert to GIFs

### ISSUE THREAD

**Issue by caffeineandfoxes** [Gifox/Tracker#62]
Often I find myself wanting to convert an existing video clip to a GIF for easy sharing. While I've turned to online conversion tools to meet this need, there are times where the contents of videos are too sensitive to trust with services that may be storing uploaded files. While looking for solutions to this problem, I thought of Gifox, as this is my go-to tool for generating GIFs already.

**Ideally, this feature would allow users to drop or send a video clip to Gifox, and Gifox would generate a GIF from the input based on the existing settings for capturing GIFs directly through the tool.**

**Comment by louiealmeda** [comment]
It will be great to see this feature being supported

**Comment by ianbytchek** [comment]
Yes! We've been busy with a lot of stuff and this is definitely on the roadmap! Bare with us! 😉

**Comment by rogierslag** [comment]
Still on the roadmap?

**Comment by ianbytchek** [comment]
Implemented in 2.2.0! ✌️
