### ISSUE TITLE
unable to screen capture

### ISSUE THREAD

**Issue by shanalogic** [gifox/tracker#63]
I've been using gifox successfully for a month and now it's stopped recording my videos when I use the selected area option. I've restarted, uninstalled and reinstalled, tried recording less, etc. Nothing works!

It does save for the entire window option but that's a total drag because the files are so large.

Side note: It ACTS like it's recording but when I hit the stop button, nothing is being saved.

Help? I love this app and am super frustrated!! 

Thanks,
Shana

**Comment by ianbytchek** [comment]
This is very-very strange. If anyone experienced anything like this, please let know?

The algorithm for recording / saving screen vs. window selection is practically the same. The only thing that is different is user interface – window recording can be stopped from the status bar or shortcut, screen area recording can be stopped using same methods + from the control pane, where users occasionally confuse stop and cancel buttons.

<div align="center"><img src="https://user-images.githubusercontent.com/1086845/29403247-d6cd0a92-8348-11e7-98cf-cd82ff069d0b.png" width="300"></div>

Try stopping recording using a shortcut, default is <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>5</kbd>, or from status bar – click on the stop icon:

<div align="center"><img src="https://user-images.githubusercontent.com/1086845/29403832-8fac8172-834a-11e7-8a92-7decaa4911c7.png" width="300"></div>

If that is out of the way and doesn't solve this, try completely resetting preferences and data: first, make sure Gifox isn't running, open Terminal and run `rm -rf ~/Library/Containers/com.gifox.gifox && killall kill cfprefsd`.

Launch Gifox, you should see the welcome screen asking to select the output directory. If so, the application is reset to it's original state, the recordings list should also appear empty.
