### ISSUE TITLE
HTML select not displaying in window mode

### ISSUE THREAD

**Issue by mike182uk** [gifox/tracker#65]
Howdy 👋 

I think i've come across a bug (`1.3.0` on `macOS Sierra 10.12.6`)

When in window mode, a `select` form element does not show correctly:

**Window mode**

![select-hidden](https://user-images.githubusercontent.com/991592/29729717-2c6c62bc-89d5-11e7-8ea0-0c656679c04c.gif)

**Area mode**

![select-shown](https://user-images.githubusercontent.com/991592/29729718-2c731120-89d5-11e7-9d12-d7e06ce4f2ed.gif)

This happens in all browsers i've tried (Chrome, Safari, Firefox)

**Comment by ianbytchek** [comment]
Yo! Yes this is a known problem less pretty described in #55. Dropdowns and menus use their own tiny windows to display contents, but Gifox is already tracking the main window and not aware of others. Should be fixed soon! 🤓

**Comment by ianbytchek** [comment]
@mike182uk updated #55 with further comments, please take a look! Gonna close this one.
