### ISSUE TITLE
Gifox crashes when I'm trying to take a screenshot after updating it to 1.3.0.

### ISSUE THREAD

**Issue by gh640** [gifox/tracker#66]
I've been using this great app for over 1 year without any problem but it stopped working after I updated it to 1.3.0. Every time I try to start capturing, gifox shuts down... This was not the case bofore I updated it.

I wonder if this is the update migration bug or something and I reinstalled it and tried capturing. But it doesn't work. FYI, I used AppCleaner to delete config files fo Gifox.

My MacOS version is OS X El Capitan 10.11.6. Maybe, has this version been excluded from the supported MacOS?

Any help would be appreciated.

**Comment by ianbytchek** [comment]
Does it do it right when you click record, during recording or when / after you stopped the recording? Did you have a chance to send bug report?

**Comment by gh640** [comment]
Thank you for your reaction. 

When I just click either the icon for area recording or the icon for window recording, Gifox always shuts down and the recording doesn't start since I updated it to 1.3.0.

I don't have the environment now and will try to send a bug report in a few days.

**Comment by ianbytchek** [comment]
Hmmm. Alright. Please send the report and use the same name in the form, so we can cross-reference it. Let me know when this is done, I'll investigate. Thank you!

**Comment by gh640** [comment]
I'm sorry for my late reply. 

I've sent some reports from the Gifox Problem Reporter. I used my user name gh640 there and I believe you can find them. Thanks!

**Comment by ianbytchek** [comment]
This is perfect, got details of both issues. Will be fixed in the upcoming release! And sorry for the trouble! 🤓

**Comment by gh640** [comment]
I'm glad to hear that. I like the app and am looking forward to the next release! Thank you very much 😃

**Comment by ianbytchek** [comment]
The issue was related to certain keyboard layouts, mostly Asian, not being handled while setting up hotkeys. Happened in places where Gifox would show hotkey information, including selection screen and shortcut preferences.

This is fixed and will be released shortly, until then the workaround is to switch to European keyboard layout while using the app. Apologies for inconvenience! 🤕

**Comment by gh640** [comment]
@ianbytchek Thank you for addressing the issue! Surely I use Japanese keyboard layout on the machine in which I met the problem.

I'm looking forward to the release. Thanks again 😃

**Comment by gh640** [comment]
@ianbytchek I confirmed the screenshot function of Gifox works again after I updated it to version 1.3.1. Thank you.
