### ISSUE TITLE
It stopped working again.

### ISSUE THREAD

**Issue by jbucaran** [gifox/tracker#68]
Suddenly, I am unable to get gifox to work at all. 

The problem first started when I tried to capture in fullscreen.

**Comment by ianbytchek** [comment]
Hey Jorge, apologies for not responding to your bug reports, got piled and lost under other messages. 😖 The [issue occurs when using Japanese or other Asian keyboard layout](https://github.com/gifox/tracker/issues/66), we've addressed this in the upcoming release, the immediate workaround for now is to use ASCII supporting keyboard layout while using Gifox, like English.

<div align="center"><img width="267px" src="https://user-images.githubusercontent.com/1086845/30423788-fe953d8e-9954-11e7-8661-719eef60f6ae.png"></div>

**Comment by jbucaran** [comment]
@ianbytchek Awesome! Look forward to that release and regret having learnt Japanese! 😏
