### ISSUE TITLE
Crashes every time

### ISSUE THREAD

**Issue by redandrobin** [gifox/tracker#71]
I've also submitted an in-app report. App continually crashes, I hit stop when complete and the app just crashes and disappears from top nav bar. :(

**Comment by ianbytchek** [comment]
Hey, thanks a bunch for posting and confirming this. There seems to be a bug with OS X 10.10 Yosemite and reason we still haven't published in App Store. We're looking into this now, will post updates here.

**Comment by redandrobin** [comment]
Thanks for the update - looking forward to a fix 👍

**Comment by ianbytchek** [comment]
Update is published, would appreciate if can check and confirm, direct [download](https://d320fod95jjzc.cloudfront.net/gifox/010400.02.dmg).
