### ISSUE TITLE
Add option to record mouse clicks.

### ISSUE THREAD

**Issue by JorgeBucaran** [gifox/tracker#72]
Would you consider adding an option to record mouse clicks? When the mouse clicks somewhere there should be a visual indication (on the recorded video) that the screen was clicked on that location.

**Comment by ianbytchek** [comment]
Hey Jorge! This is planned in #27. Hopefully end of this year or very early next.

**Comment by JorgeBucaran** [comment]
@ianbytchek Yay! Thanks for the swift response! 🎉
