### ISSUE TITLE
Disable watermark by default

### ISSUE THREAD

**Issue by dimitrieh** [gifox/tracker#74]
Congrats on the new release, still i have rant a bit 😉 

I shouldn't have to find out as a licensed user especially that I have to disable a water mark in order to get a propperly working gif. I sometimes make gifs of very small areas, which was now entirely obfusciated by a water mark.. bad ux imo.

Imo its also a slightly poor way of introducing a pay wall. Imo I would disable certain options, limit size of gif or time of gif.. so also free users can use it.. but thats just my opinion ;)

PS: the stop button after the new record red dot feature is barely visible, indicating a disabled state which is confusing

**Comment by dimitrieh** [comment]
cc: @ianbytchek

**Comment by ianbytchek** [comment]
Thanks @dimitrieh, will review and consider! 👍

**Comment by ianbytchek** [comment]
Default-enabled watermark is gone. We also have a 10-second time limit in free version, but planning to switch to frame limit, so users have a little more flexibility. Regarding the button, I'll keep that in mind when next revisiting the toolset, but imo red gets a little lost on black, so I was resistant towards using red for stop icon too. As usual, thanks for input!

**Comment by dimitrieh** [comment]
thanks @ianbytchek 👍 great to see continuous progress !
