### ISSUE TITLE
Modal disappears with menu bar when enabling "Automatically hide and show the menu bar"

### ISSUE THREAD

**Issue by nasimoyz** [gifox/tracker#75]
I use the "Automatically hide and show the menu bar" option to save space on my laptop.
System Preferences > General
![image](https://user-images.githubusercontent.com/1500565/34597448-b2ed246a-f1b4-11e7-9919-9897518365c5.png)

With this option enabled, the Gifox modal will disappear when the menu bar hides (even if your mouse remains hovering over the modal):
https://imgur.com/0RBmvCd

Expected behaviour: to persist after bar hides like the JetBrains Toolbox modal does in the above (Imgur) GIF.

**Comment by nasimoyz** [comment]
cc: @ianbytchek

**Comment by ianbytchek** [comment]
Ha, so that's what it is! Thanks @nasimoyz!

**Comment by ianbytchek** [comment]
@nasimoyz, again, thanks for reporting this! We've reworked status bar item from the ground up and now it feels really rock solid! 💪 Let me know if there's anything else?
