### ISSUE TITLE
Gifox won't open after update

### ISSUE THREAD

**Issue by mike182uk** [gifox/tracker#82]
Whenever Gifox updates itself, when i go to re-launch Gifox i always get the error message:

> You can’t open the application “Gifox.app” because it may be damaged or incomplete.

I then have to go to the Gifox website and re-download Gifox. Its been happening for the last few versions for me, only just got round to reporting it.

**Comment by ianbytchek** [comment]
Hmmm… 😕 Any chance you have both App Store and direct-download versions, but been using direct-download one lately. There's a chance macOS confuses them and automatically updates. If you have any ideas why this might be happening, please share? Would also help if you can upload that damaged version next time.

**Comment by mike182uk** [comment]
Nah i always use the direct-download version.

Next time it happens i'll grab the damaged version to get across to you somehow.

If i can access an older version via direct download i can try updating again to repro the issue?

**Comment by ianbytchek** [comment]
Would be ace if you could! [1.5.0](https://s3.eu-central-1.amazonaws.com/dstlalgzor/gifox/010500.00.dmg) and [1.4.0](https://s3.eu-central-1.amazonaws.com/dstlalgzor/gifox/010400.02.dmg) are at your disposal!

**Comment by ianbytchek** [comment]
@mike182uk does it happen with the latest update? 🤔

**Comment by ianbytchek** [comment]
Glad to hear. Cool, I'm gonna close this down. If this or anything out of line happens again, please let know! Again, thanks for reporting! 🍻
