### ISSUE TITLE
Keyboard being over ridden when recording

### ISSUE THREAD

**Issue by cryogenx** [Gifox/Tracker#88]
When recording a gif the keyboard doesn't work right in Microsoft remote desktop, number keys and numeric pad is unresponsive and causes strange navigational issues...

just bought the app because it looks great and cant use it for what I need it for :-(

**Comment by cryogenx** [comment]
Another update: I tried it using MS Remote Desktop version 8.0.43 and had no issue, the issue still exists with MS Remote Desktop 10.1.8

So I've found a workaround but it would be interesting to know why this is happening

**Comment by ianbytchek** [comment]
Interesting. Will investigate and let you know the findings.

**Comment by ianbytchek** [comment]
I'm gonna close this it. There were no similar reports as far as I can remember, so I assume this has more to do with MS Remote Desktop. The fact that v8 works and v10 doesn't indicate there were some changes in the way it handles events. There were some big changes in areas of user input capturing, so the way both apps play together may also have changed. If this is still an issue, please feel free to reopen? ✌️
