### ISSUE TITLE
Version 1.6.1 is not working under El Capitan and Sierra

### ISSUE THREAD

**Issue by ianbytchek** [gifox/tracker#89]
Several users have reported to have issues with the recent 1.6.1 update under OS X 10.11 El Capitan and macOS 10.12 Sierra. Seems like macOS 10.13 High Sierra doesn't share this fate? 🤔

We're looking into this. Apologies to those who has been affected by this – please revert to earlier version 1.6.0 for the time being, which can be downloaded [here](https://dstlalgzor.s3.amazonaws.com/gifox/010600.00.dmg).

**Comment by cryogenx** [comment]
is 1.6.1 available on the appstore yet?

**Comment by ianbytchek** [comment]
New build has been published for direct download. Awaiting review from Apple and Setapp, will be with you shortly!
