### ISSUE TITLE
Not playing along nicely with bartender

### ISSUE THREAD

**Issue by ianbytchek** [gifox/tracker#9]
[Bartender](https://www.macbartender.com/) – organises menu bar apps, for some reason gifox not moved into it's bar, reported by @yannickoo.

**Comment by yannickoo** [comment]
We can close this issue – I tested it again with the latest version and since the black overlay on my screen is not there anymore this isn't an open question. So no issues with Bartender, I managed it to move it into the Bartender bar and use Gifox from there :)
